@echo off
setlocal enabledelayedexpansion

:: ============================================================
:: setup_tunnel.bat - Configure and install Behike tunnel
:: Creates tunnel, DNS routes, config, and Windows service
:: ============================================================

echo.
echo ============================================================
echo   Cloudflare Tunnel Setup - Behike
echo ============================================================
echo.

:: Check for admin privileges
net session >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] This script must be run as Administrator.
    echo         Right-click CMD and select "Run as administrator"
    pause
    exit /b 1
)

:: Verify cloudflared is installed
where cloudflared >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] cloudflared is not installed.
    echo         Run install_cloudflared.bat first.
    pause
    exit /b 1
)

set "CF_DIR=C:\behique\cloudflare"
if not exist "%CF_DIR%" mkdir "%CF_DIR%"

:: -----------------------------------------------
:: STEP 1: Authenticate with Cloudflare
:: -----------------------------------------------
echo.
echo [STEP 1/5] Authenticating with Cloudflare...
echo           This will open your browser. Log in and authorize.
echo.
pause

cloudflared tunnel login
if %errorlevel% neq 0 (
    echo [ERROR] Authentication failed. Try again.
    pause
    exit /b 1
)
echo [OK] Authenticated with Cloudflare.

:: -----------------------------------------------
:: STEP 2: Create the tunnel
:: -----------------------------------------------
echo.
echo [STEP 2/5] Creating tunnel "behike"...
echo.

:: Check if tunnel already exists
cloudflared tunnel list | findstr /i "behike" >nul 2>&1
if %errorlevel% equ 0 (
    echo [OK] Tunnel "behike" already exists.
    echo.
    echo Existing tunnels:
    cloudflared tunnel list
    echo.
) else (
    cloudflared tunnel create behike
    if %errorlevel% neq 0 (
        echo [ERROR] Failed to create tunnel.
        echo         If tunnel already exists, this is fine. Continuing...
    ) else (
        echo [OK] Tunnel "behike" created.
    )
)

:: Get tunnel ID
echo.
echo [*] Retrieving tunnel ID...
for /f "tokens=1" %%i in ('cloudflared tunnel list 2^>nul ^| findstr /i "behike"') do set "TUNNEL_ID=%%i"

if not defined TUNNEL_ID (
    echo [ERROR] Could not find tunnel ID for "behike".
    echo         Check output of: cloudflared tunnel list
    pause
    exit /b 1
)

echo [OK] Tunnel ID: %TUNNEL_ID%

:: -----------------------------------------------
:: STEP 3: Create config.yml
:: -----------------------------------------------
echo.
echo [STEP 3/5] Creating config.yml...
echo.

:: Find credentials file
set "CRED_FILE="
set "CF_HOME=%USERPROFILE%\.cloudflared"
if exist "%CF_HOME%\%TUNNEL_ID%.json" (
    set "CRED_FILE=%CF_HOME%\%TUNNEL_ID%.json"
)

if not defined CRED_FILE (
    echo [WARN] Credentials file not found at %CF_HOME%\%TUNNEL_ID%.json
    echo        You may need to update the credentials-file path in config.yml manually.
    set "CRED_FILE=%CF_HOME%\%TUNNEL_ID%.json"
)

:: Write config.yml
(
echo # Behike Cloudflare Tunnel Configuration
echo # Generated by setup_tunnel.bat
echo # Tunnel: behike ^(%TUNNEL_ID%^)
echo.
echo tunnel: %TUNNEL_ID%
echo credentials-file: %CRED_FILE%
echo.
echo # Metrics server for monitoring ^(optional^)
echo metrics: localhost:2000
echo.
echo # Ingress rules - maps domains to local services
echo ingress:
echo   # Storefront - behike.co
echo   - hostname: behike.co
echo     service: http://localhost:8080
echo     originRequest:
echo       noTLSVerify: true
echo.
echo   # Storefront - behike.store ^(same backend, different domain^)
echo   - hostname: behike.store
echo     service: http://localhost:8080
echo     originRequest:
echo       noTLSVerify: true
echo.
echo   # Wildcard subdomains ^(uncomment when needed^)
echo   # - hostname: "*.behike.co"
echo   #   service: http://localhost:8080
echo.
echo   # Catch-all rule ^(required, must be last^)
echo   - service: http_status:404
) > "%CF_DIR%\config.yml"

if %errorlevel% neq 0 (
    echo [ERROR] Failed to write config.yml
    pause
    exit /b 1
)

echo [OK] Config written to %CF_DIR%\config.yml

:: Also copy to default cloudflared config location
copy "%CF_DIR%\config.yml" "%CF_HOME%\config.yml" >nul 2>&1
echo [OK] Config copied to %CF_HOME%\config.yml

:: -----------------------------------------------
:: STEP 4: Create DNS routes
:: -----------------------------------------------
echo.
echo [STEP 4/5] Creating DNS routes...
echo.

echo [*] Creating DNS route for behike.co...
cloudflared tunnel route dns behike behike.co
if %errorlevel% neq 0 (
    echo [WARN] DNS route for behike.co may already exist or domain not configured.
    echo        Check Cloudflare dashboard if this fails.
) else (
    echo [OK] DNS route created: behike.co -> tunnel behike
)

echo.
echo [*] Creating DNS route for behike.store...
cloudflared tunnel route dns behike behike.store
if %errorlevel% neq 0 (
    echo [WARN] DNS route for behike.store may already exist or domain not configured.
    echo        Check Cloudflare dashboard if this fails.
) else (
    echo [OK] DNS route created: behike.store -> tunnel behike
)

:: -----------------------------------------------
:: STEP 5: Install as Windows service
:: -----------------------------------------------
echo.
echo [STEP 5/5] Installing as Windows service...
echo.

:: Check if service already exists
sc query cloudflared >nul 2>&1
if %errorlevel% equ 0 (
    echo [*] Existing cloudflared service found. Removing first...
    cloudflared service uninstall
    timeout /t 2 /nobreak >nul
)

cloudflared service install
if %errorlevel% neq 0 (
    echo [WARN] Service installation had issues.
    echo        You can start the tunnel manually with start_tunnel.bat
) else (
    echo [OK] cloudflared installed as Windows service.
    echo [*] Starting service...
    net start cloudflared
    if %errorlevel% neq 0 (
        echo [WARN] Service failed to start. Check config and try: net start cloudflared
    ) else (
        echo [OK] Service started. Tunnel is live.
    )
)

:: -----------------------------------------------
:: Summary
:: -----------------------------------------------
echo.
echo ============================================================
echo   Setup Complete
echo ============================================================
echo.
echo   Tunnel Name:   behike
echo   Tunnel ID:     %TUNNEL_ID%
echo   Config:        %CF_DIR%\config.yml
echo   Credentials:   %CRED_FILE%
echo.
echo   Routes:
echo     behike.co     -> localhost:8080
echo     behike.store  -> localhost:8080
echo.
echo   Service:       cloudflared (Windows Service)
echo.
echo   Commands:
echo     status.bat       - Check tunnel status
echo     stop_tunnel.bat  - Stop the tunnel
echo     start_tunnel.bat - Start the tunnel
echo.
echo   Dashboard: https://one.dash.cloudflare.com
echo ============================================================
echo.
pause
