#!/usr/bin/env python3
"""
BIOS Daily Report Generator - Phase 7.
Runs all ingestion, generates intelligence, produces a report,
and optionally sends to Telegram.

Usage:
    python3 bios/scheduler/daily_report.py           # Full pipeline + report
    python3 bios/scheduler/daily_report.py --telegram # Also send via Telegram
"""

import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent
BIOS_DIR = BASE_DIR / "bios"
STORAGE_DIR = BIOS_DIR / "storage"
REPORTS_DIR = BIOS_DIR / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def run_step(name, command):
    """Run a pipeline step."""
    print(f"  [{name}]...")
    try:
        result = subprocess.run(
            command.split(), cwd=str(BASE_DIR),
            capture_output=True, text=True, timeout=120
        )
        if result.returncode != 0:
            print(f"    WARN: {name} exited with {result.returncode}")
        return result.returncode == 0
    except Exception as e:
        print(f"    ERROR: {e}")
        return False


def load_json(path):
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return []


def generate_report():
    """Generate a text report from current data."""
    signals = load_json(STORAGE_DIR / "signals.json")
    insights = load_json(STORAGE_DIR / "insights.json")
    polymarket = load_json(STORAGE_DIR / "polymarket.json")

    now = datetime.now(timezone.utc)
    report_lines = []
    report_lines.append("=" * 50)
    report_lines.append("BIOS DAILY INTELLIGENCE BRIEF")
    report_lines.append(now.strftime("%Y-%m-%d %H:%M UTC"))
    report_lines.append("=" * 50)

    # Signal summary
    from collections import Counter
    source_counts = Counter(s.get("source", "?") for s in signals)
    report_lines.append(f"\nSIGNALS: {len(signals)} from {len(source_counts)} sources")

    # Top narratives by tag
    tag_counts = Counter()
    for s in signals:
        for t in s.get("tags", []):
            tag_counts[t] += 1
    report_lines.append(f"\nTOP NARRATIVES:")
    for tag, count in tag_counts.most_common(5):
        report_lines.append(f"  {tag}: {count} mentions")

    # Insights
    if insights:
        actionable = [i for i in insights if i.get("action_level") == "ACTIONABLE"]
        monitor = [i for i in insights if i.get("action_level") == "MONITOR"]

        if actionable:
            report_lines.append(f"\nACTIONABLE ({len(actionable)}):")
            for ins in actionable:
                name = ins.get("pattern", "?").replace("_", " ").title()
                conf = ins.get("confidence", 0)
                report_lines.append(f"  {name} ({conf:.0%})")
                for e in ins.get("effects", [])[:3]:
                    report_lines.append(f"    {e}")
                if ins.get("pr_relevance", 0) >= 0.5:
                    report_lines.append(f"    PR: {ins.get('pr_note', '')}")

        if monitor:
            report_lines.append(f"\nMONITOR ({len(monitor)}):")
            for ins in monitor:
                name = ins.get("pattern", "?").replace("_", " ").title()
                report_lines.append(f"  {name} ({ins.get('confidence', 0):.0%})")

    # Polymarket
    markets = polymarket.get("markets", [])
    if markets:
        report_lines.append(f"\nPOLYMARKET TOP 5:")
        for m in markets[:5]:
            q = m.get("question", "?")[:50]
            try:
                price = float(m.get("outcomePrices", "[0.5]").strip("[]").split(",")[0].strip('"'))
            except Exception:
                price = 0.5
            report_lines.append(f"  {price:.0%} - {q}")

    # PR signals
    pr_sigs = [s for s in signals if "puerto_rico" in s.get("tags", [])]
    if pr_sigs:
        report_lines.append(f"\nPUERTO RICO ({len(pr_sigs)} signals):")
        for s in pr_sigs[:3]:
            report_lines.append(f"  {s.get('title', '')[:70]}")

    report_lines.append(f"\n{'='*50}")
    report_lines.append("End of brief. Generated by BIOS.")
    report_lines.append(f"{'='*50}")

    return "\n".join(report_lines)


def send_telegram(text):
    """Send report via Telegram."""
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID", "")
    if not token or not chat_id:
        print("  Telegram not configured. Skipping.")
        return False
    try:
        import urllib.request
        data = json.dumps({"chat_id": chat_id, "text": text[:4000]}).encode()
        req = urllib.request.Request(
            f"https://api.telegram.org/bot{token}/sendMessage",
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            return resp.status == 200
    except Exception as e:
        print(f"  Telegram error: {e}")
        return False


def main():
    print("  BIOS Daily Report Pipeline")
    print("  " + "=" * 40)

    # Step 1: Ingest
    run_step("News", "python3 bios/ingestion/news_fetcher.py")
    run_step("Polymarket", "python3 bios/ingestion/polymarket_fetcher.py")
    run_step("Reddit", "python3 bios/ingestion/reddit_signal.py")

    # Step 2: Intelligence
    run_step("Intelligence", "python3 bios/intelligence/causal_engine.py")

    # Step 3: Generate report
    print("\n  Generating report...")
    report = generate_report()

    # Save report
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_file = REPORTS_DIR / f"daily_{date_str}.txt"
    with open(report_file, "w") as f:
        f.write(report)
    print(f"  Saved: {report_file}")

    # Print report
    print("\n" + report)

    # Send to Telegram if requested
    if "--telegram" in sys.argv:
        print("\n  Sending to Telegram...")
        if send_telegram(report):
            print("  Sent.")
        else:
            print("  Failed to send.")


if __name__ == "__main__":
    main()
