#!/usr/bin/env python3
"""Batch Product Prep Wave 2 - 25 more products."""

import os, shutil
from pathlib import Path

REPO = Path(os.path.expanduser("~/behique"))
SRC = REPO / "Ceiba/projects/content-empire/products"
DST = REPO / "READY-TO-SELL/products-organized"

PRODUCTS = [
    {"slug": "adhd-budget", "pdf": "adhd-budget-guide.pdf", "name": "ADHD Budget Guide", "price": "$4.99", "pages": 13, "tags": "ADHD, budget, finance, money, productivity", "title": "ADHD\nBUDGET\nGUIDE", "modules": ["Budget Setup", "Tracking", "ADHD Hacks", "Savings"], "desc": "Budgeting is hard. With ADHD it's harder. This guide gives you a system that works with your brain, not against it.\n\n13 pages. Fill-in format. No apps. No subscriptions.", "summary": "1 PDF guide (13 pages)\nADHD-friendly budget system\nFill-in worksheets\nNo apps needed", "receipt": "Welcome to Behike. Budget like your brain wants to. behike.gumroad.com"},
    {"slug": "adhd-finance", "pdf": "adhd-finance-guide.pdf", "name": "ADHD Finance Guide", "price": "$9.99", "pages": 20, "tags": "ADHD, finance, money, investing, personal finance", "title": "ADHD\nFINANCE\nGUIDE", "modules": ["Spending Audit", "Debt Plan", "Savings System", "Investing Basics", "Automation"], "desc": "The complete money guide for ADHD brains. Spending, saving, investing, debt — all in a system you can actually follow.\n\n20 pages.", "summary": "1 PDF guide (20 pages)\nComplete ADHD finance system\nDebt payoff plan\nInvesting basics", "receipt": "Welcome to Behike. Get your money right. behike.gumroad.com"},
    {"slug": "ai-agent-kit", "pdf": "ai-agent-installer-kit.pdf", "name": "AI Agent Installer Kit", "price": "$19.99", "pages": 19, "tags": "AI, agents, automation, installation, business", "title": "AI AGENT\nINSTALLER\nKIT", "modules": ["Agent Types", "Installation", "Configuration", "Client Delivery", "Pricing"], "desc": "Install AI agents for businesses and charge $500-2000 per setup. This kit shows you exactly how.\n\n19 pages. Every step from finding clients to delivering the agent.", "summary": "1 PDF kit (19 pages)\nAI agent installation guide\nClient acquisition\nPricing framework", "receipt": "Welcome to Behike. Start installing AI agents. behike.gumroad.com"},
    {"slug": "ai-chatbot", "pdf": "ai-chatbot-guide.pdf", "name": "AI Chatbot Guide", "price": "$9.99", "pages": 16, "tags": "AI, chatbot, automation, customer service, business", "title": "AI CHATBOT\nGUIDE", "modules": ["Chatbot Types", "Setup", "Training", "Deployment", "Optimization"], "desc": "Build AI chatbots for businesses. Customer service, lead gen, FAQ automation.\n\n16 pages.", "summary": "1 PDF guide (16 pages)\nChatbot setup + training\nDeployment guide\nOptimization tips", "receipt": "Welcome to Behike. Build chatbots. behike.gumroad.com"},
    {"slug": "ai-content-machine", "pdf": "ai-content-machine-kit.pdf", "name": "AI Content Machine Kit", "price": "$9.99", "pages": 15, "tags": "AI, content, automation, writing, social media", "title": "AI CONTENT\nMACHINE\nKIT", "modules": ["Content Pipeline", "AI Writing", "Repurposing", "Scheduling", "Analytics"], "desc": "Turn one idea into 30 pieces of content using AI. Blog posts, social media, newsletters, videos — all from one input.\n\n15 pages.", "summary": "1 PDF kit (15 pages)\nContent multiplication system\nAI writing prompts\nRepurposing framework", "receipt": "Welcome to Behike. One idea. 30 content pieces. behike.gumroad.com"},
    {"slug": "ai-employee", "pdf": "ai-employee-guide.pdf", "name": "AI Employee Guide", "price": "$19.99", "pages": 36, "tags": "AI, automation, employee, system, self-hosted", "title": "AI EMPLOYEE\nGUIDE", "modules": ["Architecture", "Setup", "Fleet Management", "Task Delegation", "Monitoring", "Troubleshooting"], "desc": "Build an AI system that works while you sleep. Three computers. Zero monthly cost. This is the complete guide to building your own AI employee.\n\n36 pages. Architecture diagrams. Copy-paste commands.", "summary": "1 PDF guide (36 pages)\nFull AI system architecture\nFleet management scripts\nCopy-paste setup commands", "receipt": "Welcome to Behike. Your AI employee is ready. behike.gumroad.com"},
    {"slug": "ai-security", "pdf": "ai-security-guide.pdf", "name": "AI Security Guide", "price": "$9.99", "pages": 17, "tags": "AI, security, privacy, safety, self-hosted", "title": "AI SECURITY\nGUIDE", "modules": ["Threat Model", "Data Privacy", "Prompt Injection", "API Security", "Self-Hosting"], "desc": "Secure your AI systems. Prompt injection defense, data privacy, API security, self-hosting best practices.\n\n17 pages.", "summary": "1 PDF guide (17 pages)\nAI threat modeling\nPrompt injection defense\nSelf-hosting security", "receipt": "Welcome to Behike. Secure your AI. behike.gumroad.com"},
    {"slug": "ai-writing", "pdf": "ai-writing-workflows.pdf", "name": "AI Writing Workflows", "price": "$9.99", "pages": 15, "tags": "AI, writing, workflows, content, productivity", "title": "AI WRITING\nWORKFLOWS", "modules": ["Blog Posts", "Newsletters", "Social Media", "Product Descriptions", "Editing"], "desc": "5 complete AI writing workflows. Blog posts, newsletters, social media, product descriptions, editing.\n\nNot prompts. Full workflows you can follow start to finish.\n\n15 pages.", "summary": "1 PDF guide (15 pages)\n5 complete workflows\nStart-to-finish processes\nAI prompt templates", "receipt": "Welcome to Behike. Write faster with AI. behike.gumroad.com"},
    {"slug": "content-franchise", "pdf": "content-franchise-kit.pdf", "name": "Content Franchise Kit", "price": "$14.99", "pages": 33, "tags": "content, franchise, scaling, delegation, business", "title": "CONTENT\nFRANCHISE\nKIT", "modules": ["Content System", "Delegation", "Templates", "SOPs", "Scaling", "Revenue Model"], "desc": "Build a content business you can franchise. SOPs, templates, delegation systems. 33 pages of everything you need to scale content production.\n\nPDF format.", "summary": "1 PDF kit (33 pages)\nContent production SOPs\nDelegation templates\nFranchise revenue model", "receipt": "Welcome to Behike. Franchise your content. behike.gumroad.com"},
    {"slug": "creators-revenue", "pdf": "creators-revenue-blueprint.pdf", "name": "Creator's Revenue Blueprint", "price": "$9.99", "pages": 20, "tags": "creator, revenue, monetization, income streams, business", "title": "CREATOR'S\nREVENUE\nBLUEPRINT", "modules": ["Revenue Streams", "Pricing", "Digital Products", "Services", "Passive Income"], "desc": "7 revenue streams every creator should have. Digital products, services, affiliates, sponsors, communities, courses, templates.\n\n20 pages. Fill-in format.", "summary": "1 PDF blueprint (20 pages)\n7 revenue streams\nPricing framework\nPassive income systems", "receipt": "Welcome to Behike. Diversify your income. behike.gumroad.com"},
    {"slug": "digital-pricing", "pdf": "digital-product-pricing-guide.pdf", "name": "Digital Product Pricing Guide", "price": "$4.99", "pages": 12, "tags": "pricing, digital products, strategy, revenue, value", "title": "DIGITAL\nPRODUCT\nPRICING", "modules": ["Pricing Psychology", "Value Stacking", "Tiered Pricing", "Bundles"], "desc": "Stop guessing your prices. Psychology-based pricing framework for digital products. Value stacking, tiered pricing, bundle strategy.\n\n12 pages.", "summary": "1 PDF guide (12 pages)\nPricing psychology framework\nValue stacking method\nBundle strategy", "receipt": "Welcome to Behike. Price with confidence. behike.gumroad.com"},
    {"slug": "ghost-writer", "pdf": "ghost-writer-kit.pdf", "name": "Ghost Writer Kit", "price": "$9.99", "pages": 12, "tags": "ghostwriting, writing, freelance, AI, content", "title": "GHOST\nWRITER\nKIT", "modules": ["Finding Clients", "Voice Matching", "AI Assistance", "Pricing"], "desc": "Start a ghostwriting business with AI. Find clients, match their voice, deliver fast.\n\n12 pages.", "summary": "1 PDF kit (12 pages)\nGhostwriting workflow\nAI voice matching\nClient acquisition", "receipt": "Welcome to Behike. Write for others. Get paid. behike.gumroad.com"},
    {"slug": "gumroad-starter", "pdf": "gumroad-starter-kit.pdf", "name": "Gumroad Starter Kit", "price": "$4.99", "pages": 20, "tags": "gumroad, starter, digital products, selling, beginner", "title": "GUMROAD\nSTARTER\nKIT", "modules": ["Account Setup", "First Product", "Listing", "Pricing", "Launch"], "desc": "Everything you need to get your first product on Gumroad. From account setup to first sale.\n\n20 pages. Step by step.", "summary": "1 PDF kit (20 pages)\nAccount setup guide\nFirst product creation\nLaunch checklist", "receipt": "Welcome to Behike. Get on Gumroad today. behike.gumroad.com"},
    {"slug": "n8n-automation", "pdf": "n8n-automation-pack.pdf", "name": "n8n Automation Pack", "price": "$14.99", "pages": 21, "tags": "n8n, automation, workflows, no-code, integration", "title": "N8N\nAUTOMATION\nPACK", "modules": ["n8n Setup", "Workflow Design", "Integrations", "Error Handling", "Deployment", "Templates"], "desc": "15+ automation workflows for n8n. Email, social media, CRM, data processing. Copy-paste and customize.\n\n21 pages.", "summary": "1 PDF pack (21 pages)\n15+ workflow templates\nn8n setup guide\nIntegration examples", "receipt": "Welcome to Behike. Automate everything. behike.gumroad.com"},
    {"slug": "n8n-solopreneur", "pdf": "n8n-solopreneur-guide.pdf", "name": "n8n for Solopreneurs", "price": "$9.99", "pages": 14, "tags": "n8n, solopreneur, automation, business, workflows", "title": "N8N FOR\nSOLO-\nPRENEURS", "modules": ["Why n8n", "Setup", "Business Workflows", "Client Automation"], "desc": "n8n automation specifically for solopreneurs. Client onboarding, invoice reminders, content scheduling, lead capture.\n\n14 pages.", "summary": "1 PDF guide (14 pages)\nSolopreneur-specific workflows\nClient automation\nLead capture setup", "receipt": "Welcome to Behike. Automate your solo business. behike.gumroad.com"},
    {"slug": "polymarket", "pdf": "polymarket-strategy-guide.pdf", "name": "Polymarket Strategy Guide", "price": "$9.99", "pages": 21, "tags": "polymarket, prediction markets, trading, strategy, crypto", "title": "POLYMARKET\nSTRATEGY\nGUIDE", "modules": ["Market Analysis", "Position Sizing", "Risk Management", "Data Sources", "Automation"], "desc": "Trade prediction markets with a system. Market analysis, position sizing, risk management. Data-driven, not gut-feeling.\n\n21 pages.", "summary": "1 PDF guide (21 pages)\nMarket analysis framework\nPosition sizing system\nRisk management rules", "receipt": "Welcome to Behike. Trade smarter. behike.gumroad.com"},
    {"slug": "reel-factory", "pdf": "reel-factory-system.pdf", "name": "Reel Factory System", "price": "$9.99", "pages": 13, "tags": "reels, instagram, tiktok, video, content, automation", "title": "REEL\nFACTORY\nSYSTEM", "modules": ["Content Pipeline", "AI Scripts", "Editing Workflow", "Scheduling"], "desc": "Produce 30 reels a month without burning out. AI scripts, batch editing, scheduling system.\n\n13 pages.", "summary": "1 PDF system (13 pages)\n30 reels/month pipeline\nAI script generation\nBatch editing workflow", "receipt": "Welcome to Behike. Produce reels on autopilot. behike.gumroad.com"},
    {"slug": "second-brain", "pdf": "solopreneur-second-brain.pdf", "name": "Solopreneur Second Brain", "price": "$9.99", "pages": 15, "tags": "second brain, knowledge management, productivity, notes, system", "title": "SOLOPRENEUR\nSECOND\nBRAIN", "modules": ["Capture", "Organize", "Connect", "Create", "Review"], "desc": "Build a second brain for your business. Capture ideas, organize knowledge, connect dots, create from your library.\n\n15 pages. The PARA method adapted for solopreneurs.", "summary": "1 PDF guide (15 pages)\nSecond brain framework\nPARA method adapted\nKnowledge management system", "receipt": "Welcome to Behike. Build your second brain. behike.gumroad.com"},
    {"slug": "telegram-bot", "pdf": "telegram-bot-for-business.pdf", "name": "Telegram Bot for Business", "price": "$9.99", "pages": 25, "tags": "telegram, bot, automation, business, python", "title": "TELEGRAM\nBOT FOR\nBUSINESS", "modules": ["Bot Setup", "Commands", "Automation", "Notifications", "Deployment", "Integration"], "desc": "Build a Telegram bot for your business. Customer notifications, order tracking, team communication, automated responses.\n\n25 pages. Python code included.", "summary": "1 PDF guide (25 pages)\nTelegram bot setup\nPython code examples\nBusiness automation workflows", "receipt": "Welcome to Behike. Build your business bot. behike.gumroad.com"},
    {"slug": "youtube-blueprint", "pdf": "youtube-channel-blueprint.pdf", "name": "YouTube Channel Blueprint", "price": "$9.99", "pages": 20, "tags": "youtube, channel, content, growth, monetization", "title": "YOUTUBE\nCHANNEL\nBLUEPRINT", "modules": ["Niche Selection", "Content Strategy", "SEO", "Production", "Monetization"], "desc": "Launch and grow a YouTube channel from zero. Niche selection, content strategy, SEO, production workflow, monetization.\n\n20 pages.", "summary": "1 PDF blueprint (20 pages)\nChannel launch guide\nYouTube SEO system\nMonetization timeline", "receipt": "Welcome to Behike. Start your channel. behike.gumroad.com"},
    {"slug": "youtube-money", "pdf": "youtube-monetization-guide.pdf", "name": "YouTube Monetization Guide", "price": "$9.99", "pages": 23, "tags": "youtube, monetization, revenue, adsense, sponsorships", "title": "YOUTUBE\nMONETIZATION\nGUIDE", "modules": ["AdSense", "Sponsorships", "Affiliates", "Products", "Memberships", "Super Chats"], "desc": "6 ways to make money on YouTube. AdSense, sponsorships, affiliates, digital products, memberships, super chats.\n\n23 pages. Real numbers.", "summary": "1 PDF guide (23 pages)\n6 monetization methods\nReal revenue breakdowns\nSponsor outreach templates", "receipt": "Welcome to Behike. Monetize your channel. behike.gumroad.com"},
    {"slug": "zero-to-sale", "pdf": "zero-to-first-sale.pdf", "name": "Zero to First Sale", "price": "$4.99", "pages": 19, "tags": "first sale, beginner, ecommerce, digital products, launch", "title": "ZERO TO\nFIRST\nSALE", "modules": ["Product Selection", "Platform Setup", "Listing", "Traffic", "Conversion"], "desc": "From nothing to your first online sale. The shortest path. No fluff.\n\n19 pages.", "summary": "1 PDF guide (19 pages)\nShortest path to first sale\nPlatform comparison\nTraffic + conversion basics", "receipt": "Welcome to Behike. Make your first sale. Today. behike.gumroad.com"},
    {"slug": "mastery-builders", "pdf": "mastery-for-builders.pdf", "name": "Mastery for Builders", "price": "$9.99", "pages": 19, "tags": "mastery, building, productivity, skills, growth", "title": "MASTERY\nFOR\nBUILDERS", "modules": ["Skill Stacking", "Deliberate Practice", "Feedback Loops", "Compounding", "Ship Daily"], "desc": "How to get good at building things. Skill stacking, deliberate practice, feedback loops, shipping daily.\n\n19 pages.", "summary": "1 PDF guide (19 pages)\nSkill stacking framework\nDeliberate practice system\nDaily shipping habit", "receipt": "Welcome to Behike. Get good. Ship daily. behike.gumroad.com"},
]

def create_product(p):
    folder = DST / p["slug"]
    if folder.exists():
        print(f"  SKIP: {p['slug']}")
        return False
    folder.mkdir(parents=True, exist_ok=True)
    src = SRC / p["pdf"]
    if src.exists(): shutil.copy2(src, folder / p["pdf"])
    info = f"""GUMROAD LISTING INFO\n====================\n\nName: {p['name']}\nPrice: {p['price']}\nURL slug: {p['slug']}\nCall to action: Buy this\nCategory: Self Improvement > Productivity\nTags: {p['tags']}\nReceipt button: Download Guide\n\nDESCRIPTION:\n{p['desc']}\n\nSUMMARY (You'll get...):\n{p['summary']}\n\nRECEIPT MESSAGE:\n{p['receipt']}\n"""
    (folder / "GUMROAD_INFO.txt").write_text(info)

    # Generate cover HTML
    title_html = "<br>".join(p["title"].split("\n"))
    mods = "".join(f'<span class="mod">{m}</span>' for m in p["modules"])
    cover = f'''<!DOCTYPE html><html><head><meta charset="UTF-8"><style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap');*{{margin:0;padding:0;box-sizing:border-box;}}body{{width:1280px;height:720px;background:#0a0a0a;color:#e0e0e0;font-family:'Inter',sans-serif;display:flex;flex-direction:column;justify-content:center;padding:60px 80px;overflow:hidden;position:relative;}}.pain{{text-decoration:line-through;color:#555;font-size:14px;margin:2px 0;}}.title{{font-size:38px;font-weight:900;color:#fff;margin:14px 0 8px;line-height:1.1;}}.cyan-line{{width:80px;height:3px;background:#00e5ff;margin-bottom:14px;}}.modules{{display:flex;flex-wrap:wrap;gap:6px;}}.mod{{background:#111;border:1px solid #1a1a1a;padding:4px 10px;border-radius:4px;font-size:11px;color:#aaa;}}.brand{{position:absolute;bottom:30px;right:40px;font-size:11px;color:#333;letter-spacing:3px;text-transform:uppercase;}}</style></head><body><div class="pain">Another 40-hour course</div><div class="pain">Generic advice that doesn't work</div><div class="title">{title_html}</div><div class="cyan-line"></div><div class="modules">{mods}</div><div class="brand">BEHIKE</div></body></html>'''
    (folder / "cover.html").write_text(cover)

    thumb_title = "<br>".join(p["title"].split("\n")[:2])
    thumb = f'''<!DOCTYPE html><html><head><meta charset="UTF-8"><style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@700;900&display=swap');*{{margin:0;padding:0;box-sizing:border-box;}}body{{width:600px;height:600px;background:#0a0a0a;color:#fff;font-family:'Inter',sans-serif;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:60px;overflow:hidden;}}.title{{font-size:36px;font-weight:900;line-height:1.15;margin-bottom:16px;}}.cyan-line{{width:60px;height:3px;background:#00e5ff;margin-bottom:20px;}}.brand{{font-size:11px;color:#333;letter-spacing:4px;text-transform:uppercase;}}</style></head><body><div class="title">{thumb_title}</div><div class="cyan-line"></div><div class="brand">BEHIKE</div></body></html>'''
    (folder / "thumbnail.html").write_text(thumb)

    print(f"  DONE: {p['slug']} ({p['pages']}p, {p['price']})")
    return True

print(f"\n{'='*50}\n  WAVE 2: {len(PRODUCTS)} products\n{'='*50}\n")
created = sum(1 for p in PRODUCTS if create_product(p))
print(f"\n  Created: {created}")
print(f"  Total: {len(list(DST.iterdir()))}")
