#!/usr/bin/env python3
"""Batch Spanish Product Prep - prep ES variants for Gumroad."""
import os, shutil
from pathlib import Path

REPO = Path(os.path.expanduser("~/behique"))
SRC = REPO / "Ceiba/projects/content-empire/products/es"
DST = REPO / "READY-TO-SELL/products-organized"

PRODUCTS = [
    {"slug": "metodo-behike-es", "pdf": "el-metodo-behike.pdf", "name": "El M\u00e9todo Behike", "price": "$19.99", "tags": "behike, metodo, negocio, ADHD, sistema, espanol", "desc": "8 cap\u00edtulos. Visi\u00f3n, Domain Stacking, ADHD Builder's Edge, Content Waterfall, AI Content Engine, Value Ladder, Ship It.\n\nEl sistema exacto que us\u00e9 para construir 100+ productos en 2 semanas con ADHD y Claude Code.\n\nPDF formato. 34 p\u00e1ginas. En espa\u00f1ol.", "summary": "1 PDF (34 p\u00e1ginas, 8 cap\u00edtulos)\nEl M\u00e9todo Behike en espa\u00f1ol\nSistema para constructores con ADHD", "receipt": "Bienvenido a Behike. El m\u00e9todo es tuyo. Construye. behike.gumroad.com", "title": "EL M\u00c9TODO\nBEHIKE", "modules": ["Visi\u00f3n", "Domain Stack", "ADHD Edge", "Content", "AI Engine", "Value Ladder"]},
    {"slug": "amazon-fba-es", "pdf": "guia-amazon-fba.pdf", "name": "Gu\u00eda Amazon FBA (Espa\u00f1ol)", "price": "$9.99", "tags": "amazon, FBA, ecommerce, espanol, negocio", "desc": "Empieza a vender en Amazon FBA. Investigaci\u00f3n de productos, proveedores, optimizaci\u00f3n de listings, PPC b\u00e1sico.\n\nEn espa\u00f1ol. PDF.", "summary": "1 PDF gu\u00eda en espa\u00f1ol\nInvestigaci\u00f3n de productos\nProveedores + PPC", "receipt": "Bienvenido a Behike. Empieza tu negocio en Amazon. behike.gumroad.com", "title": "GU\u00cdA\nAMAZON FBA", "modules": ["Productos", "Proveedores", "Listings", "PPC"]},
    {"slug": "chatbot-ia-es", "pdf": "guia-chatbot-ia.pdf", "name": "Gu\u00eda Chatbot IA (Espa\u00f1ol)", "price": "$9.99", "tags": "chatbot, IA, automatizacion, espanol, negocio", "desc": "Construye chatbots de IA para negocios. Servicio al cliente, generaci\u00f3n de leads, automatizaci\u00f3n de FAQ.\n\nEn espa\u00f1ol. PDF.", "summary": "1 PDF gu\u00eda en espa\u00f1ol\nSetup de chatbot\nAutomatizaci\u00f3n de servicio", "receipt": "Bienvenido a Behike. Construye chatbots. behike.gumroad.com", "title": "GU\u00cdA\nCHATBOT IA", "modules": ["Tipos", "Setup", "Entrenamiento", "Deploy"]},
    {"slug": "empleado-ia-es", "pdf": "guia-empleado-ia.pdf", "name": "Gu\u00eda Empleado IA (Espa\u00f1ol)", "price": "$19.99", "tags": "IA, empleado, automatizacion, sistema, espanol", "desc": "Construye un sistema de IA que trabaja mientras duermes. Tres computadoras. Cero costo mensual.\n\n36 p\u00e1ginas. En espa\u00f1ol.", "summary": "1 PDF gu\u00eda (36 p\u00e1ginas) en espa\u00f1ol\nArquitectura completa\nComandos copy-paste", "receipt": "Bienvenido a Behike. Tu empleado IA est\u00e1 listo. behike.gumroad.com", "title": "GU\u00cdA\nEMPLEADO IA", "modules": ["Arquitectura", "Setup", "Fleet", "Tareas", "Monitoreo"]},
    {"slug": "ecommerce-guia-es", "pdf": "guia-ecommerce.pdf", "name": "Gu\u00eda E-Commerce (Espa\u00f1ol)", "price": "$9.99", "tags": "ecommerce, tienda online, espanol, negocio", "desc": "Todo lo que necesitas para lanzar una tienda online. Plataformas, productos, marketing, envios.\n\nEn espa\u00f1ol.", "summary": "1 PDF gu\u00eda en espa\u00f1ol\nPlataformas comparadas\nMarketing + envios", "receipt": "Bienvenido a Behike. Lanza tu tienda. behike.gumroad.com", "title": "GU\u00cdA\nE-COMMERCE", "modules": ["Plataformas", "Productos", "Marketing", "Env\u00edos"]},
    {"slug": "tienda-autoalojada-es", "pdf": "guia-tienda-autoalojada.pdf", "name": "Gu\u00eda Tienda Autoalojada (Espa\u00f1ol)", "price": "$4.99", "tags": "tienda, autoalojada, hosting gratis, espanol", "desc": "Construye una tienda online por $0/mes. HTML + Gumroad + hosting gratis.\n\nDeja de pagar $29/mes por Shopify. En espa\u00f1ol.", "summary": "1 PDF gu\u00eda en espa\u00f1ol\nTienda sin costo mensual\nHosting gratis", "receipt": "Bienvenido a Behike. Deja de pagar Shopify. behike.gumroad.com", "title": "TIENDA\nAUTOALOJADA", "modules": ["HTML", "Gumroad", "Hosting Gratis"]},
    {"slug": "noticias-ia-es", "pdf": "guia-rastreador-noticias-ia.pdf", "name": "Rastreador Noticias IA (Espa\u00f1ol)", "price": "$4.99", "tags": "noticias, IA, rastreador, RSS, espanol", "desc": "18 fuentes RSS. Puntuaci\u00f3n de impacto. Rastreo de entidades. Digest en HTML.\n\nConstruye tu propio rastreador de noticias. En espa\u00f1ol.", "summary": "1 PDF gu\u00eda en espa\u00f1ol\n18 fuentes RSS\nSistema de puntuaci\u00f3n", "receipt": "Bienvenido a Behike. Mant\u00e9nte al d\u00eda. behike.gumroad.com", "title": "RASTREADOR\nNOTICIAS IA", "modules": ["RSS", "Puntuaci\u00f3n", "Entidades", "Digest"]},
    {"slug": "solopreneur-os-es", "pdf": "solopreneur-os.pdf", "name": "Solopreneur OS (Espa\u00f1ol)", "price": "$12.99", "tags": "solopreneur, sistema operativo, ADHD, productividad, espanol", "desc": "5 m\u00f3dulos. 13 ejercicios. Visi\u00f3n, Domain Stack, Content Engine, Monetizaci\u00f3n, Operaciones Diarias.\n\nEl sistema para manejar un negocio con ADHD. En espa\u00f1ol.", "summary": "1 PDF workbook (36 p\u00e1ginas) en espa\u00f1ol\n13 ejercicios\nSistema ADHD-friendly", "receipt": "Bienvenido a Behike. Tu sistema operativo est\u00e1 listo. behike.gumroad.com", "title": "SOLOPRENEUR\nOS", "modules": ["Visi\u00f3n", "Domain", "Contenido", "Dinero", "Operaciones"]},
    {"slug": "ebay-dropshipping-es", "pdf": "guia-ebay-dropshipping.pdf", "name": "Gu\u00eda eBay Dropshipping (Espa\u00f1ol)", "price": "$9.99", "tags": "ebay, dropshipping, ecommerce, espanol", "desc": "Dropshipping en eBay paso a paso. Investigaci\u00f3n, listados, env\u00edos, automatizaci\u00f3n.\n\nEn espa\u00f1ol.", "summary": "1 PDF gu\u00eda en espa\u00f1ol\nDropshipping en eBay\nAutomatizaci\u00f3n", "receipt": "Bienvenido a Behike. Empieza en eBay. behike.gumroad.com", "title": "GU\u00cdA EBAY\nDROPSHIPPING", "modules": ["Investigaci\u00f3n", "Listados", "Env\u00edos", "Auto"]},
]

def create(p):
    folder = DST / p["slug"]
    if folder.exists(): print(f"  SKIP: {p['slug']}"); return False
    folder.mkdir(parents=True, exist_ok=True)
    src = SRC / p["pdf"]
    if src.exists(): shutil.copy2(src, folder / p["pdf"])
    info = f"GUMROAD LISTING INFO\n====================\n\nName: {p['name']}\nPrice: {p['price']}\nURL slug: {p['slug']}\nCall to action: Buy this\nCategory: Self Improvement > Productivity\nTags: {p['tags']}\nReceipt button: Download Guide\n\nDESCRIPTION:\n{p['desc']}\n\nSUMMARY:\n{p['summary']}\n\nRECEIPT MESSAGE:\n{p['receipt']}\n"
    (folder / "GUMROAD_INFO.txt").write_text(info)
    title_html = "<br>".join(p["title"].split("\n"))
    mods = "".join(f'<span class="mod">{m}</span>' for m in p["modules"])
    cover = f'<!DOCTYPE html><html><head><meta charset="UTF-8"><style>@import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap");*{{margin:0;padding:0;box-sizing:border-box;}}body{{width:1280px;height:720px;background:#0a0a0a;color:#e0e0e0;font-family:"Inter",sans-serif;display:flex;flex-direction:column;justify-content:center;padding:60px 80px;overflow:hidden;position:relative;}}.badge{{display:inline-block;background:#ffd700;color:#000;padding:3px 12px;border-radius:4px;font-size:11px;font-weight:800;margin-bottom:12px;}}.title{{font-size:38px;font-weight:900;color:#fff;margin:8px 0;line-height:1.1;}}.title span{{color:#00e5ff;}}.line{{width:80px;height:3px;background:#00e5ff;margin:12px 0;}}.modules{{display:flex;flex-wrap:wrap;gap:6px;}}.mod{{background:#111;border:1px solid #1a1a1a;padding:4px 10px;border-radius:4px;font-size:11px;color:#888;}}.brand{{position:absolute;bottom:30px;right:40px;font-size:11px;color:#333;letter-spacing:3px;}}</style></head><body><div class="badge">ESPA\u00d1OL</div><div class="title"><span>{title_html}</span></div><div class="line"></div><div class="modules">{mods}</div><div class="brand">BEHIKE</div></body></html>'
    (folder / "cover.html").write_text(cover)
    thumb = f'<!DOCTYPE html><html><head><meta charset="UTF-8"><style>@import url("https://fonts.googleapis.com/css2?family=Inter:wght@700;900&display=swap");*{{margin:0;padding:0;box-sizing:border-box;}}body{{width:600px;height:600px;background:#0a0a0a;color:#00e5ff;font-family:"Inter",sans-serif;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:60px;overflow:hidden;}}.badge{{background:#ffd700;color:#000;padding:3px 12px;border-radius:4px;font-size:10px;font-weight:800;margin-bottom:16px;}}.title{{font-size:36px;font-weight:900;line-height:1.15;margin-bottom:16px;}}.line{{width:60px;height:3px;background:#00e5ff;margin-bottom:20px;}}.brand{{font-size:11px;color:#333;letter-spacing:4px;}}</style></head><body><div class="badge">ES</div><div class="title">{title_html}</div><div class="line"></div><div class="brand">BEHIKE</div></body></html>'
    (folder / "thumbnail.html").write_text(thumb)
    print(f"  DONE: {p['slug']} ({p['price']})")
    return True

print(f"\n{'='*50}\n  SPANISH PRODUCTS: {len(PRODUCTS)}\n{'='*50}\n")
created = sum(1 for p in PRODUCTS if create(p))
print(f"\n  Created: {created}")
print(f"  Total: {len(list(DST.iterdir()))}")
