#!/usr/bin/env python3
# Copyright 2026 Behike. All rights reserved.
"""
Ceiba Autonomous Orchestrator. The "always be building" system.

Reads pending tasks, picks the highest-value one that can be done without
human input, executes it, logs the result, and moves to the next task.

Every time Kalani opens a new Claude Code session, there's new work completed.

Usage:
    python3 ceiba_autonomous.py --run            # execute one task
    python3 ceiba_autonomous.py --plan           # show what would be done, don't do it
    python3 ceiba_autonomous.py --status         # show autonomous log summary
    python3 ceiba_autonomous.py --continuous     # keep going until time limit (default 2h)
    python3 ceiba_autonomous.py --continuous --limit 60   # 60 minute limit
    python3 ceiba_autonomous.py --help

Logs: Ceiba/AUTONOMOUS_LOG.md
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path

# --- Paths ---
TOOLS_DIR = Path(__file__).parent
PROJECT_DIR = TOOLS_DIR.parent
CEIBA_DIR = PROJECT_DIR / "Ceiba"
NEWS_DIR = CEIBA_DIR / "news"

MASTER_TODO = CEIBA_DIR / "MASTER_TODO.md"
IDEAS_BACKLOG = CEIBA_DIR / "IDEAS_BACKLOG.md"
AUTONOMOUS_LOG = CEIBA_DIR / "AUTONOMOUS_LOG.md"
VOICE_BIBLE = CEIBA_DIR / "VOICE_BIBLE.md"

# Dynamic files (date-stamped)
TODAY = datetime.now().strftime("%Y-%m-%d")
MISSED_IDEAS = CEIBA_DIR / f"MISSED_IDEAS_{TODAY}.md"
ANALYTICS_FILE = NEWS_DIR / "analytics.json"
CALENDAR_FILE = NEWS_DIR / f"calendar-{TODAY}.json"
DAILY_DIR = NEWS_DIR / "daily" / TODAY

# Tool paths
DAILY_CONTENT = TOOLS_DIR / "daily_content.py"
CONTENT_CALENDAR = TOOLS_DIR / "content_calendar.py"
PERFORMANCE_TRACKER = TOOLS_DIR / "performance_tracker.py"
MD_TO_PDF = TOOLS_DIR / "md_to_pdf.py"
VOICE_CHECKER = TOOLS_DIR / "voice_checker.py"
SCRIPT_WRITER = TOOLS_DIR / "script_writer.py"
CAROUSEL_GEN = TOOLS_DIR / "carousel_generator.py"
OVERNIGHT = TOOLS_DIR / "overnight.sh"
NEWS_PIPELINE = TOOLS_DIR / "ai_news_pipeline.py"
NEWSLETTER = TOOLS_DIR / "newsletter_writer.py"
EBOOK_BUILDER = TOOLS_DIR / "ebook_builder.py"

# --- Priority tiers ---
TIER_REVENUE = 3      # Revenue-generating tasks
TIER_AUDIENCE = 2     # Audience-building tasks
TIER_INFRA = 1        # Infrastructure/maintenance tasks

# Strings that mark a task as needing human input
HUMAN_BLOCKERS = [
    "BLOCKED on Kalani",
    "needs Kalani",
    "manual",
    "in person",
    "browser",
    "paperwork",
    "visit ",
    "sign up",
    "purchase",
    "pay ",
    "buy ",
    "file LLC",
    "EIN",
    "bank account",
    "domain",
]


def timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def log_action(task_name, description, files_changed, duration_sec, status="COMPLETED"):
    """Append an entry to AUTONOMOUS_LOG.md."""
    AUTONOMOUS_LOG.parent.mkdir(parents=True, exist_ok=True)

    entry = f"""
---

### [{timestamp()}] {status}: {task_name}

**What:** {description}
**Duration:** {duration_sec:.1f}s
**Files touched:**
"""
    for f in files_changed:
        entry += f"- `{f}`\n"
    entry += "\n"

    if not AUTONOMOUS_LOG.exists():
        header = f"""# Ceiba Autonomous Log
# What got done while you were away.
# Generated by ceiba_autonomous.py
# Copyright 2026 Behike.

"""
        AUTONOMOUS_LOG.write_text(header + entry)
    else:
        existing = AUTONOMOUS_LOG.read_text()
        # Insert after header (after first blank line)
        parts = existing.split("\n\n", 1)
        if len(parts) == 2:
            AUTONOMOUS_LOG.write_text(parts[0] + "\n\n" + entry + parts[1])
        else:
            with open(AUTONOMOUS_LOG, "a") as f:
                f.write(entry)


def run_tool(tool_path, args=None, timeout=300):
    """Run a Python/Bash tool and return (success, stdout, stderr, duration)."""
    if not tool_path.exists():
        return False, "", f"Tool not found: {tool_path}", 0.0

    start = time.time()
    cmd = []
    if str(tool_path).endswith(".py"):
        cmd = [sys.executable, str(tool_path)]
    elif str(tool_path).endswith(".sh"):
        cmd = ["bash", str(tool_path)]
    else:
        cmd = [str(tool_path)]

    if args:
        cmd.extend(args)

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(PROJECT_DIR),
        )
        duration = time.time() - start
        return result.returncode == 0, result.stdout, result.stderr, duration
    except subprocess.TimeoutExpired:
        duration = time.time() - start
        return False, "", f"Timed out after {timeout}s", duration
    except Exception as e:
        duration = time.time() - start
        return False, "", str(e), duration


# --- Task Discovery ---

def find_stale_pdfs():
    """Find markdown files whose PDFs are older than the source."""
    stale = []
    products_dir = PROJECT_DIR / "themes" / "behike-store"
    content_dirs = [
        CEIBA_DIR / "projects",
        PROJECT_DIR / "legal",
        products_dir,
    ]
    for d in content_dirs:
        if not d.exists():
            continue
        for md_file in d.rglob("*.md"):
            pdf_file = md_file.with_suffix(".pdf")
            if pdf_file.exists():
                if md_file.stat().st_mtime > pdf_file.stat().st_mtime:
                    stale.append((md_file, pdf_file))
            # Also check in a pdfs/ subdirectory
            alt_pdf = md_file.parent / "pdfs" / (md_file.stem + ".pdf")
            if alt_pdf.exists():
                if md_file.stat().st_mtime > alt_pdf.stat().st_mtime:
                    stale.append((md_file, alt_pdf))
    return stale


def check_daily_content_generated():
    """Check if today's daily content bundle exists."""
    bundle_dir = NEWS_DIR / "daily-bundles"
    if not bundle_dir.exists():
        return False
    today_bundles = list(bundle_dir.glob(f"*{TODAY}*"))
    return len(today_bundles) > 0


def check_calendar_exists():
    """Check if today's content calendar exists."""
    return CALENDAR_FILE.exists()


def check_news_fetched():
    """Check if news has been fetched today."""
    articles = NEWS_DIR / "articles.json"
    if not articles.exists():
        return False
    mtime = datetime.fromtimestamp(articles.stat().st_mtime)
    return mtime.date() == datetime.now().date()


def parse_master_todo_tasks():
    """Parse MASTER_TODO.md for actionable, non-blocked tasks."""
    if not MASTER_TODO.exists():
        return []

    tasks = []
    content = MASTER_TODO.read_text()
    current_section = ""
    current_tier = TIER_INFRA

    for line in content.split("\n"):
        # Detect section headers
        if line.startswith("## CRITICAL"):
            current_section = "critical"
            current_tier = TIER_REVENUE
        elif line.startswith("## HIGH"):
            current_section = "high"
            current_tier = TIER_REVENUE
        elif line.startswith("## MEDIUM") or line.startswith("## CONTENT"):
            current_section = "medium"
            current_tier = TIER_AUDIENCE
        elif line.startswith("## LOW") or line.startswith("## INFRASTRUCTURE"):
            current_section = "low"
            current_tier = TIER_INFRA
        elif line.startswith("## "):
            # Generic section detection based on keywords
            lower = line.lower()
            if any(w in lower for w in ["revenue", "product", "money", "sales"]):
                current_tier = TIER_REVENUE
            elif any(w in lower for w in ["content", "audience", "growth", "post"]):
                current_tier = TIER_AUDIENCE
            else:
                current_tier = TIER_INFRA

        # Detect task lines
        if line.strip().startswith("### ") or (line.strip().startswith("- [ ]")):
            task_text = line.strip().lstrip("#- []").strip()

            # Check if blocked on human
            is_blocked = False
            # Look ahead a few lines for blocker info
            idx = content.index(line) if line in content else -1
            if idx >= 0:
                context = content[idx:idx + 500]
                for blocker in HUMAN_BLOCKERS:
                    if blocker.lower() in context.lower():
                        is_blocked = True
                        break

            # Check machine assignment
            automatable = True
            if "Machine: Kalani" in (content[idx:idx + 500] if idx >= 0 else ""):
                automatable = False
                is_blocked = True

            if not is_blocked and automatable and task_text:
                tasks.append({
                    "name": task_text,
                    "tier": current_tier,
                    "section": current_section,
                    "source": "MASTER_TODO",
                })

    return tasks


def build_task_queue():
    """
    Build a prioritized queue of tasks that can be executed autonomously.
    Returns list of dicts sorted by priority (highest first).
    """
    tasks = []

    # --- Check automated pipeline tasks ---

    # 1. News fetching (audience building, runs daily)
    if not check_news_fetched() and NEWS_PIPELINE.exists():
        tasks.append({
            "name": "Fetch AI news",
            "tier": TIER_AUDIENCE,
            "action": "news_fetch",
            "description": "Fetch and score today's AI news articles",
            "source": "pipeline",
        })

    # 2. Content calendar generation
    if not check_calendar_exists() and CONTENT_CALENDAR.exists():
        tasks.append({
            "name": "Generate content calendar",
            "tier": TIER_AUDIENCE,
            "action": "calendar",
            "description": "Generate today's content posting calendar",
            "source": "pipeline",
        })

    # 3. Daily content generation
    if not check_daily_content_generated() and DAILY_CONTENT.exists():
        tasks.append({
            "name": "Generate daily content bundle",
            "tier": TIER_AUDIENCE,
            "action": "daily_content",
            "description": "Generate full day's content (carousels, captions, posts)",
            "source": "pipeline",
        })

    # 4. Stale PDF regeneration
    stale_pdfs = find_stale_pdfs()
    if stale_pdfs and MD_TO_PDF.exists():
        for md_file, pdf_file in stale_pdfs[:5]:  # Cap at 5 per run
            tasks.append({
                "name": f"Regenerate PDF: {md_file.name}",
                "tier": TIER_INFRA,
                "action": "pdf_regen",
                "description": f"Rebuild {pdf_file.name} (source changed)",
                "source": "stale_pdf",
                "data": {"md": str(md_file), "pdf": str(pdf_file)},
            })

    # 5. Performance insights generation
    if ANALYTICS_FILE.exists() and PERFORMANCE_TRACKER.exists():
        try:
            mtime = datetime.fromtimestamp(
                (NEWS_DIR / "performance-insights.json").stat().st_mtime
            )
            insights_stale = mtime.date() < datetime.now().date()
        except (FileNotFoundError, OSError):
            insights_stale = True

        if insights_stale:
            tasks.append({
                "name": "Generate performance insights",
                "tier": TIER_AUDIENCE,
                "action": "insights",
                "description": "Analyze content performance and generate optimization insights",
                "source": "pipeline",
            })

    # 6. Voice check on recent content
    recent_content = []
    for d in [NEWS_DIR / "posts", NEWS_DIR / "carousels"]:
        if d.exists():
            for f in d.rglob("*.md"):
                if (datetime.now() - datetime.fromtimestamp(f.stat().st_mtime)).days < 1:
                    recent_content.append(f)

    if recent_content and VOICE_CHECKER.exists():
        tasks.append({
            "name": "Voice check recent content",
            "tier": TIER_INFRA,
            "action": "voice_check",
            "description": f"Run voice bible checker on {len(recent_content)} recent files",
            "source": "pipeline",
            "data": {"files": [str(f) for f in recent_content[:10]]},
        })

    # 7. Parse MASTER_TODO for automatable tasks
    todo_tasks = parse_master_todo_tasks()
    tasks.extend(todo_tasks)

    # 8. Check MISSED_IDEAS for buildable items
    if MISSED_IDEAS.exists():
        content = MISSED_IDEAS.read_text()
        # Look for items marked as "Buildable now? Yes"
        buildable_count = content.lower().count("buildable now? yes")
        if buildable_count > 0:
            tasks.append({
                "name": "Review missed ideas for quick builds",
                "tier": TIER_REVENUE,
                "action": "missed_ideas",
                "description": f"Found {buildable_count} buildable ideas in MISSED_IDEAS",
                "source": "missed_ideas",
            })

    # Sort by tier (highest first), then by source priority
    source_priority = {"pipeline": 0, "stale_pdf": 1, "missed_ideas": 2, "MASTER_TODO": 3}
    tasks.sort(key=lambda t: (-t["tier"], source_priority.get(t.get("source", ""), 99)))

    return tasks


# --- Task Execution ---

def execute_task(task):
    """Execute a single task. Returns (success, files_changed, description)."""
    action = task.get("action", "")
    files_changed = []

    if action == "news_fetch":
        ok, stdout, stderr, dur = run_tool(NEWS_PIPELINE, timeout=120)
        if ok:
            files_changed.append("Ceiba/news/articles.json")
        return ok, files_changed, f"News fetch {'succeeded' if ok else 'failed'}: {stderr[:200] if not ok else ''}", dur

    elif action == "calendar":
        ok, stdout, stderr, dur = run_tool(CONTENT_CALENDAR, ["--generate"], timeout=60)
        if ok:
            files_changed.append(f"Ceiba/news/calendar-{TODAY}.json")
            files_changed.append(f"Ceiba/news/calendar-{TODAY}.md")
        return ok, files_changed, f"Calendar generation {'succeeded' if ok else 'failed'}", dur

    elif action == "daily_content":
        ok, stdout, stderr, dur = run_tool(DAILY_CONTENT, timeout=300)
        if ok:
            files_changed.append(f"Ceiba/news/daily-bundles/{TODAY}/")
        return ok, files_changed, f"Daily content {'generated' if ok else 'failed'}", dur

    elif action == "pdf_regen":
        data = task.get("data", {})
        md_path = data.get("md", "")
        pdf_path = data.get("pdf", "")
        if md_path and pdf_path:
            ok, stdout, stderr, dur = run_tool(MD_TO_PDF, [md_path, pdf_path], timeout=60)
            if ok:
                files_changed.append(pdf_path)
            return ok, files_changed, f"PDF regen {'succeeded' if ok else 'failed'}: {Path(md_path).name}", dur
        return False, [], "Missing md/pdf paths", 0.0

    elif action == "insights":
        ok, stdout, stderr, dur = run_tool(PERFORMANCE_TRACKER, ["--insights"], timeout=60)
        if ok:
            files_changed.append("Ceiba/news/performance-insights.json")
        return ok, files_changed, f"Insights {'generated' if ok else 'failed'}", dur

    elif action == "voice_check":
        data = task.get("data", {})
        all_ok = True
        total_dur = 0.0
        for fpath in data.get("files", []):
            ok, stdout, stderr, dur = run_tool(VOICE_CHECKER, [fpath, "--fix"], timeout=30)
            total_dur += dur
            if ok:
                files_changed.append(fpath)
            else:
                all_ok = False
        return all_ok, files_changed, f"Voice checked {len(data.get('files', []))} files", total_dur

    elif action == "missed_ideas":
        # This one just logs that the review is needed. Actual building
        # requires Claude Code to interpret the ideas file.
        return True, [], "Flagged missed ideas for next interactive session", 0.0

    else:
        # Generic MASTER_TODO task. Can't auto-execute without more context.
        # Log it as skipped so Kalani sees it was considered.
        return False, [], f"Task '{task.get('name', '?')}' needs manual execution or a dedicated tool", 0.0


# --- CLI ---

def show_plan(tasks):
    """Show what would be done without doing it."""
    tier_names = {TIER_REVENUE: "REVENUE", TIER_AUDIENCE: "AUDIENCE", TIER_INFRA: "INFRA"}
    print(f"\n  Ceiba Autonomous Planner -- {TODAY}")
    print(f"  Found {len(tasks)} actionable tasks\n")

    if not tasks:
        print("  Nothing to do. All caught up.")
        return

    for i, task in enumerate(tasks, 1):
        tier = tier_names.get(task["tier"], "?")
        action = task.get("action", "manual")
        auto = "AUTO" if action and action != "" else "MANUAL"
        desc = task.get("description", task.get("name", ""))
        source = task.get("source", "?")
        print(f"  {i:2d}. [{tier}] [{auto}] {task['name']}")
        if desc != task["name"]:
            print(f"      {desc}")
        print(f"      Source: {source}")
        print()


def show_status():
    """Show summary of autonomous log."""
    if not AUTONOMOUS_LOG.exists():
        print("\n  No autonomous activity yet. Run --run or --continuous to start.")
        return

    content = AUTONOMOUS_LOG.read_text()
    completed = content.count("COMPLETED:")
    failed = content.count("FAILED:")
    skipped = content.count("SKIPPED:")

    # Find most recent entry timestamp
    timestamps = re.findall(r"\[(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\]", content)
    last_run = timestamps[0] if timestamps else "never"

    print(f"\n  Ceiba Autonomous Status")
    print(f"  Last run: {last_run}")
    print(f"  Completed: {completed}")
    print(f"  Failed: {failed}")
    print(f"  Skipped: {skipped}")
    print(f"  Log: {AUTONOMOUS_LOG}")

    # Show last 5 entries
    entries = re.findall(r"### \[.*?\].*?(?=\n---|\Z)", content, re.DOTALL)
    if entries:
        print(f"\n  Recent activity:")
        for entry in entries[:5]:
            # Extract just the header line
            header = entry.split("\n")[0].strip("# ")
            print(f"    {header}")
    print()


def run_one(tasks):
    """Execute the highest-priority task."""
    if not tasks:
        print("  Nothing to do. All caught up.")
        return False

    # Find first task with an executable action
    for task in tasks:
        action = task.get("action", "")
        if not action:
            continue

        print(f"  Executing: {task['name']}")
        print(f"  Tier: {['', 'INFRA', 'AUDIENCE', 'REVENUE'][task['tier']]}")
        print(f"  Description: {task.get('description', '')}")
        print()

        start = time.time()
        success, files_changed, description, duration = execute_task(task)
        status = "COMPLETED" if success else "FAILED"

        log_action(task["name"], description, files_changed, duration, status)

        print(f"  Result: {status}")
        print(f"  Duration: {duration:.1f}s")
        if files_changed:
            print(f"  Files: {', '.join(files_changed)}")
        print()
        return success

    print("  No auto-executable tasks found. Remaining tasks need human input.")
    return False


def run_continuous(tasks, limit_minutes=120):
    """Keep executing tasks until done or time limit hit."""
    deadline = datetime.now() + timedelta(minutes=limit_minutes)
    completed = 0
    failed = 0

    print(f"\n  Ceiba Autonomous Mode -- CONTINUOUS")
    print(f"  Time limit: {limit_minutes} minutes (until {deadline.strftime('%H:%M')})")
    print(f"  Tasks queued: {len(tasks)}")
    print()

    while datetime.now() < deadline:
        # Rebuild queue each iteration (tasks may have been completed)
        tasks = build_task_queue()
        executable = [t for t in tasks if t.get("action")]

        if not executable:
            print(f"\n  All done. Completed: {completed}, Failed: {failed}")
            break

        task = executable[0]
        print(f"  [{datetime.now().strftime('%H:%M:%S')}] Running: {task['name']}")

        start = time.time()
        success, files_changed, description, duration = execute_task(task)
        status = "COMPLETED" if success else "FAILED"

        log_action(task["name"], description, files_changed, duration, status)

        if success:
            completed += 1
            print(f"    Done in {duration:.1f}s")
        else:
            failed += 1
            print(f"    Failed: {description[:100]}")

        # Brief pause between tasks
        time.sleep(2)

    else:
        print(f"\n  Time limit reached. Completed: {completed}, Failed: {failed}")

    # Final summary
    print(f"\n  Session summary: {completed} completed, {failed} failed")
    log_action(
        "Autonomous session ended",
        f"Completed {completed} tasks, {failed} failures, ran for {limit_minutes}min",
        [],
        0.0,
        "SESSION_END",
    )


def main():
    parser = argparse.ArgumentParser(
        description="Ceiba Autonomous Orchestrator. Always be building.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--run", action="store_true", help="Execute one task")
    parser.add_argument("--plan", action="store_true", help="Show what would be done")
    parser.add_argument("--status", action="store_true", help="Show autonomous log summary")
    parser.add_argument("--continuous", action="store_true", help="Keep going until time limit")
    parser.add_argument("--limit", type=int, default=120, help="Time limit in minutes (default: 120)")
    args = parser.parse_args()

    if not any([args.run, args.plan, args.status, args.continuous]):
        parser.print_help()
        return

    if args.status:
        show_status()
        return

    tasks = build_task_queue()

    if args.plan:
        show_plan(tasks)
    elif args.run:
        run_one(tasks)
    elif args.continuous:
        run_continuous(tasks, args.limit)


if __name__ == "__main__":
    main()
