#!/usr/bin/env python3
"""
Graph Query Layer — Programmatic API for the Vault Knowledge Graph

Lets Ceiba query the vault graph without reading raw JSON.
Supports: neighbors, find_by_type, tools_for_project, shortest_path,
graph_context (get related nodes for a topic), and stats.

Data source: ~/behique/Ceiba/vault_graph.json (generated by vault_grapher.py)

Usage as library:
    from graph_query import VaultGraph
    g = VaultGraph()
    g.neighbors("eBay-Listing-Assistant")
    g.find_by_type("project")
    g.tools_for_project("BehiqueBot")
    g.graph_context("eBay", depth=2)

Usage as CLI:
    python3 graph_query.py neighbors eBay-Listing-Assistant
    python3 graph_query.py type project
    python3 graph_query.py tools BehiqueBot
    python3 graph_query.py context eBay --depth 2
    python3 graph_query.py path HOME BehiqueBot
    python3 graph_query.py stats
    python3 graph_query.py search "scraper"
"""

import os
import json
import argparse
from collections import defaultdict, deque
from typing import Dict, List, Optional, Set, Tuple


VAULT_GRAPH = os.path.join(
    os.path.expanduser("~/behique"), "Ceiba", "vault_graph.json"
)


class VaultGraph:
    """Queryable interface to the vault knowledge graph."""

    def __init__(self, graph_path: str = VAULT_GRAPH):
        self.graph_path = graph_path
        self.nodes: Dict[str, dict] = {}
        self.edges: List[Tuple[str, str]] = []
        self.typed_edges: List[dict] = []  # [{source, target, type}]
        self.adjacency: Dict[str, Set[str]] = defaultdict(set)
        self.reverse_adj: Dict[str, Set[str]] = defaultdict(set)
        self.rel_index: Dict[str, Dict[str, List[str]]] = defaultdict(lambda: defaultdict(list))
        # rel_index[node][edge_type] = [targets]
        self.reverse_rel: Dict[str, Dict[str, List[str]]] = defaultdict(lambda: defaultdict(list))
        # reverse_rel[target][edge_type] = [sources]
        self.stats: dict = {}
        self._load()

    def _load(self):
        """Load and index the graph."""
        if not os.path.exists(self.graph_path):
            raise FileNotFoundError(f"Vault graph not found: {self.graph_path}")

        with open(self.graph_path) as f:
            data = json.load(f)

        self.nodes = data.get("nodes", {})
        raw_edges = data.get("edges", [])
        self.typed_edges = data.get("typed_edges", [])
        self.stats = data.get("stats", {})

        # Build adjacency lists from legacy edges
        for edge in raw_edges:
            if isinstance(edge, list) and len(edge) == 2:
                src, tgt = edge
                self.edges.append((src, tgt))
                self.adjacency[src].add(tgt)
                self.reverse_adj[tgt].add(src)

        # Build typed relationship index
        for te in self.typed_edges:
            src = te.get("source", "")
            tgt = te.get("target", "")
            etype = te.get("type", "wiki_link")
            if src and tgt and etype != "wiki_link":
                self.rel_index[src][etype].append(tgt)
                self.reverse_rel[tgt][etype].append(src)

    def reload(self):
        """Reload graph from disk."""
        self.nodes = {}
        self.edges = []
        self.adjacency = defaultdict(set)
        self.reverse_adj = defaultdict(set)
        self._load()

    # ============ Core Queries ============
    def neighbors(self, node: str, direction: str = "both") -> List[str]:
        """
        Get connected nodes.
        direction: "out" (links from), "in" (links to), "both"
        """
        node = self._resolve_name(node)
        if not node:
            return []

        result = set()
        if direction in ("out", "both"):
            result |= self.adjacency.get(node, set())
        if direction in ("in", "both"):
            result |= self.reverse_adj.get(node, set())
        return sorted(result)

    def find_by_type(self, node_type: str) -> List[str]:
        """Find all nodes of a given type."""
        node_type = node_type.lower()
        return sorted([
            name for name, data in self.nodes.items()
            if data.get("type", "").lower() == node_type
        ])

    def tools_for_project(self, project: str) -> List[str]:
        """Find all tools/resources linked to a project."""
        project = self._resolve_name(project)
        if not project:
            return []

        # Get all neighbors, filter to tool-like nodes
        all_connected = self.neighbors(project)
        tools = []
        for n in all_connected:
            node_data = self.nodes.get(n, {})
            node_type = node_data.get("type", "").lower()
            path = node_data.get("path", "").lower()
            # Tools are in 05-Tools or have type "tool"
            if node_type == "tool" or "tool" in path or "05-" in path:
                tools.append(n)
        return sorted(tools)

    def projects_for_tool(self, tool: str) -> List[str]:
        """Find all projects that use a tool."""
        tool = self._resolve_name(tool)
        if not tool:
            return []

        all_connected = self.neighbors(tool)
        projects = []
        for n in all_connected:
            node_data = self.nodes.get(n, {})
            path = node_data.get("path", "").lower()
            if "01-projects" in path or node_data.get("type", "").lower() == "project":
                projects.append(n)
        return sorted(projects)

    def graph_context(self, topic: str, depth: int = 2) -> Dict[str, List[str]]:
        """
        Get graph context around a topic — all nodes within N hops.
        Returns dict of {distance: [nodes]}.
        """
        start = self._resolve_name(topic)
        if not start:
            # Fuzzy search if exact match fails
            matches = self.search(topic)
            if matches:
                start = matches[0]
            else:
                return {}

        visited = {start: 0}
        queue = deque([(start, 0)])
        result = defaultdict(list)
        result[0].append(start)

        while queue:
            node, dist = queue.popleft()
            if dist >= depth:
                continue

            for neighbor in self.neighbors(node):
                if neighbor not in visited:
                    visited[neighbor] = dist + 1
                    queue.append((neighbor, dist + 1))
                    result[dist + 1].append(neighbor)

        return dict(result)

    def shortest_path(self, start: str, end: str) -> Optional[List[str]]:
        """BFS shortest path between two nodes."""
        start = self._resolve_name(start)
        end = self._resolve_name(end)
        if not start or not end:
            return None
        if start == end:
            return [start]

        visited = {start}
        queue = deque([(start, [start])])

        while queue:
            node, path = queue.popleft()
            for neighbor in self.neighbors(node):
                if neighbor == end:
                    return path + [neighbor]
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.append((neighbor, path + [neighbor]))

        return None  # No path found

    def search(self, query: str) -> List[str]:
        """
        Search nodes by name, path, tags, or content keywords.
        Returns matching node names sorted by relevance.
        """
        query_lower = query.lower()
        results = []

        for name, data in self.nodes.items():
            score = 0
            # Exact name match
            if query_lower == name.lower():
                score = 100
            # Name contains query
            elif query_lower in name.lower():
                score = 80
            # Path contains query
            elif query_lower in data.get("path", "").lower():
                score = 60
            # Tags contain query
            elif any(query_lower in t.lower() for t in data.get("tags", [])):
                score = 50
            # Links contain query
            elif any(query_lower in l.lower() for l in data.get("links", [])):
                score = 30

            if score > 0:
                results.append((score, name))

        results.sort(key=lambda x: -x[0])
        return [name for _, name in results]

    def get_node(self, name: str) -> Optional[dict]:
        """Get full node data."""
        name = self._resolve_name(name)
        if name:
            return {"name": name, **self.nodes.get(name, {})}
        return None

    def degree(self, node: str) -> dict:
        """Get in-degree and out-degree for a node."""
        node = self._resolve_name(node)
        if not node:
            return {"error": "node not found"}
        return {
            "node": node,
            "out_degree": len(self.adjacency.get(node, set())),
            "in_degree": len(self.reverse_adj.get(node, set())),
            "total_degree": len(self.neighbors(node)),
        }

    def hubs(self, top_n: int = 10) -> List[Tuple[str, int]]:
        """Find the most connected nodes."""
        degrees = []
        for name in self.nodes:
            total = len(self.neighbors(name))
            degrees.append((name, total))
        degrees.sort(key=lambda x: -x[1])
        return degrees[:top_n]

    def orphans(self) -> List[str]:
        """Find nodes with no connections."""
        return sorted([
            name for name in self.nodes
            if not self.adjacency.get(name) and not self.reverse_adj.get(name)
        ])

    def get_stats(self) -> dict:
        """Comprehensive graph statistics."""
        all_degrees = [len(self.neighbors(n)) for n in self.nodes]
        return {
            "total_nodes": len(self.nodes),
            "total_edges": len(self.edges),
            "orphans": len(self.orphans()),
            "missing_targets": self.stats.get("missing_targets", 0),
            "avg_degree": round(sum(all_degrees) / len(all_degrees), 1) if all_degrees else 0,
            "max_degree": max(all_degrees) if all_degrees else 0,
            "types": dict(sorted(
                defaultdict(int, {
                    data.get("type", "unknown"): sum(1 for _, d in self.nodes.items()
                                                     if d.get("type") == data.get("type"))
                    for _, data in self.nodes.items()
                }).items()
            )),
            "top_hubs": self.hubs(5),
        }

    # ============ Typed Relationship Queries ============
    def relationships(self, node: str, rel_type: str = None) -> Dict[str, List[str]]:
        """Get typed relationships for a node. Optionally filter by type."""
        node = self._resolve_name(node)
        if not node:
            return {}
        rels = dict(self.rel_index.get(node, {}))
        if rel_type:
            return {rel_type: rels.get(rel_type, [])}
        return rels

    def reverse_relationships(self, node: str, rel_type: str = None) -> Dict[str, List[str]]:
        """Get nodes that have typed relationships TO this node."""
        node = self._resolve_name(node)
        if not node:
            return {}
        rels = dict(self.reverse_rel.get(node, {}))
        if rel_type:
            return {rel_type: rels.get(rel_type, [])}
        return rels

    def find_by_relationship(self, rel_type: str) -> List[Tuple[str, str]]:
        """Find all edges of a given relationship type."""
        return [
            (te["source"], te["target"])
            for te in self.typed_edges
            if te.get("type") == rel_type
        ]

    def relationship_types(self) -> Dict[str, int]:
        """Get all relationship types and their counts."""
        return self.stats.get("relationship_types", {})

    # ============ Helpers ============
    def _resolve_name(self, name: str) -> Optional[str]:
        """Resolve a node name (case-insensitive, partial match)."""
        if not name:
            return None
        # Exact match
        if name in self.nodes:
            return name
        # Case-insensitive
        for n in self.nodes:
            if n.lower() == name.lower():
                return n
        # Partial match (name contains query)
        for n in self.nodes:
            if name.lower() in n.lower():
                return n
        return None


# ============ CLI ============
def main():
    parser = argparse.ArgumentParser(description="Vault Graph Query Layer")
    sub = parser.add_subparsers(dest="command")

    # neighbors
    np = sub.add_parser("neighbors", help="Get connected nodes")
    np.add_argument("node")
    np.add_argument("--dir", default="both", choices=["in", "out", "both"])

    # type
    tp = sub.add_parser("type", help="Find nodes by type")
    tp.add_argument("node_type")

    # tools
    tlp = sub.add_parser("tools", help="Find tools for a project")
    tlp.add_argument("project")

    # context
    cp = sub.add_parser("context", help="Graph context around a topic")
    cp.add_argument("topic")
    cp.add_argument("--depth", type=int, default=2)

    # path
    pp = sub.add_parser("path", help="Shortest path between nodes")
    pp.add_argument("start")
    pp.add_argument("end")

    # search
    sp = sub.add_parser("search", help="Search nodes")
    sp.add_argument("query")

    # hubs
    hp = sub.add_parser("hubs", help="Most connected nodes")
    hp.add_argument("--top", type=int, default=10)

    # rels
    rp = sub.add_parser("rels", help="Typed relationships for a node")
    rp.add_argument("node")
    rp.add_argument("--type", dest="rel_type", help="Filter by relationship type")
    rp.add_argument("--reverse", action="store_true", help="Show incoming relationships")

    # rel-types
    sub.add_parser("rel-types", help="List all relationship types")

    # stats
    sub.add_parser("stats", help="Graph statistics")

    args = parser.parse_args()
    if not args.command:
        parser.print_help()
        return

    g = VaultGraph()

    if args.command == "neighbors":
        result = g.neighbors(args.node, args.dir)
        print(f"Neighbors of '{args.node}' ({args.dir}): {len(result)}")
        for n in result:
            node = g.nodes.get(n, {})
            print(f"  {n} ({node.get('type', '?')})")

    elif args.command == "type":
        result = g.find_by_type(args.node_type)
        print(f"Nodes of type '{args.node_type}': {len(result)}")
        for n in result:
            print(f"  {n}")

    elif args.command == "tools":
        result = g.tools_for_project(args.project)
        print(f"Tools for '{args.project}': {len(result)}")
        for t in result:
            print(f"  {t}")

    elif args.command == "context":
        result = g.graph_context(args.topic, args.depth)
        for dist, nodes in sorted(result.items()):
            print(f"  Distance {dist}: {', '.join(nodes)}")

    elif args.command == "path":
        result = g.shortest_path(args.start, args.end)
        if result:
            print(f"Path ({len(result)} hops): {' → '.join(result)}")
        else:
            print(f"No path between '{args.start}' and '{args.end}'")

    elif args.command == "search":
        result = g.search(args.query)
        print(f"Search '{args.query}': {len(result)} matches")
        for n in result[:15]:
            node = g.nodes.get(n, {})
            print(f"  {n} ({node.get('type', '?')}) — {node.get('path', '')}")

    elif args.command == "hubs":
        result = g.hubs(args.top)
        print(f"Top {args.top} most connected nodes:")
        for name, degree in result:
            print(f"  {degree:3d} connections — {name}")

    elif args.command == "rels":
        if args.reverse:
            result = g.reverse_relationships(args.node, args.rel_type)
            print(f"Incoming relationships for '{args.node}':")
        else:
            result = g.relationships(args.node, args.rel_type)
            print(f"Relationships for '{args.node}':")
        if result:
            for rel_type, targets in result.items():
                print(f"  {rel_type}:")
                for t in targets:
                    print(f"    → {t}")
        else:
            print("  (none)")

    elif args.command == "rel-types":
        result = g.relationship_types()
        print("Relationship types:")
        for rtype, count in sorted(result.items(), key=lambda x: -x[1]):
            print(f"  {rtype}: {count}")

    elif args.command == "stats":
        s = g.get_stats()
        print(f"  Nodes: {s['total_nodes']}")
        print(f"  Edges: {s['total_edges']}")
        print(f"  Orphans: {s['orphans']}")
        print(f"  Missing targets: {s['missing_targets']}")
        print(f"  Avg degree: {s['avg_degree']}")
        print(f"  Max degree: {s['max_degree']}")
        print(f"  Top hubs: {', '.join(f'{n}({d})' for n, d in s['top_hubs'])}")
        # Typed relationship stats
        rt = g.relationship_types()
        if rt:
            typed_total = sum(v for k, v in rt.items() if k != "wiki_link")
            print(f"  Typed relationships: {typed_total}")
            for rtype, count in sorted(rt.items(), key=lambda x: -x[1]):
                if rtype != "wiki_link":
                    print(f"    {rtype}: {count}")


if __name__ == "__main__":
    main()
