#!/usr/bin/env python3
# Copyright 2026 Behike. All rights reserved.
"""
AI Script Generator. Uses local Ollama (qwen2.5:7b) to write video scripts
from topics. Outputs in the reel-pipeline JSON format.

Script formats:
  hook-value-cta (30s), problem-solution (60s), listicle (45s), story (90s)

Usage:
    python3 script_writer.py --topic "Why most people fail at dropshipping" --format hook
    python3 script_writer.py --topic "5 AI tools you need" --format list --language es
    python3 script_writer.py --topic "How I built my first bot" --format story
    python3 script_writer.py --topic "The real cost of free AI" --format problem
    python3 script_writer.py --from-ideas          # pick random from content-ideas.json
    python3 script_writer.py --from-ideas --count 3 # generate 3 scripts
    python3 script_writer.py --help

Requires: Ollama running at localhost:11434 with qwen2.5:7b
"""

import argparse
import json
import os
import random
import re
import sys
import urllib.request
import urllib.error
from datetime import datetime
from pathlib import Path

# --- Paths ---
TOOLS_DIR = Path(__file__).parent
PROJECT_DIR = TOOLS_DIR.parent
NEWS_DIR = PROJECT_DIR / "Ceiba" / "news"
SCRIPTS_DIR = NEWS_DIR / "scripts"
IDEAS_FILE = NEWS_DIR / "content-ideas.json"
ANALYTICS_FILE = NEWS_DIR / "analytics.json"
INSIGHTS_FILE = NEWS_DIR / "performance-insights.json"
GENERATED_LOG = NEWS_DIR / "generated-scripts.json"
REEL_STORIES_DIR = TOOLS_DIR / "reel-pipeline" / "stories"
VOICE_BIBLE = PROJECT_DIR / "Ceiba" / "VOICE_BIBLE.md"

OLLAMA_URL = os.environ.get("OLLAMA_URL", "http://localhost:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "qwen2.5:7b")

# --- Script format definitions ---
FORMATS = {
    "hook": {
        "name": "Hook-Value-CTA",
        "duration": "30s",
        "scenes": 3,
        "structure": "Hook (3s) -> Value delivery (20s) -> CTA (7s)",
        "description": "Quick, punchy content. Open with a bold statement, deliver one insight, close with follow CTA.",
    },
    "problem": {
        "name": "Problem-Solution",
        "duration": "60s",
        "scenes": 5,
        "structure": "Problem (8s) -> Agitate (10s) -> Solution intro (10s) -> How it works (22s) -> CTA (10s)",
        "description": "Name a real pain point, twist the knife, then present a clear solution.",
    },
    "list": {
        "name": "Listicle",
        "duration": "45s",
        "scenes": 5,
        "structure": "Hook (5s) -> Item 1 (8s) -> Item 2 (8s) -> Item 3 (8s) -> Bonus + CTA (16s)",
        "description": "Numbered list of tips, tools, or insights. Each item is one clear takeaway.",
    },
    "story": {
        "name": "Story",
        "duration": "90s",
        "scenes": 6,
        "structure": "Hook (5s) -> Setup (15s) -> Conflict (20s) -> Turning point (15s) -> Resolution (20s) -> Lesson + CTA (15s)",
        "description": "Personal narrative arc. Real experience, real lesson. Vulnerable but not weak.",
    },
}

# --- Voice Bible + Performance loading ---

def load_voice_bible_rules() -> str:
    """Load banned words and tone rules from the Voice Bible for prompt injection."""
    if not VOICE_BIBLE.exists():
        return ""
    try:
        content = VOICE_BIBLE.read_text(encoding="utf-8", errors="replace")
        # Extract the banned words section and tone rules
        sections = []
        capture = False
        for line in content.split("\n"):
            if "BANNED WORDS" in line or "TONE RULES" in line or "COPYWRITING RULES" in line:
                capture = True
            if capture:
                sections.append(line)
            # Stop after we have enough context
            if len(sections) > 80:
                break
        return "\n".join(sections) if sections else ""
    except Exception:
        return ""


def load_full_performance_insights() -> str:
    """Load detailed performance insights from analytics + insights files.

    Returns a formatted string for system prompt injection with:
    - Top-performing hooks
    - Topics that underperformed
    - Best content types and formats
    """
    insights_text = []

    # Load insights file first (generated by performance_tracker.py --insights)
    if INSIGHTS_FILE.exists():
        try:
            with open(INSIGHTS_FILE) as f:
                data = json.load(f)

            # Best hook styles
            hooks = data.get("best_hook_styles", [])
            if hooks:
                hook_list = []
                for h in hooks[:5]:
                    if isinstance(h, dict):
                        hook_list.append(f"{h.get('style', '?')} ({h.get('avg_engagement', 0)}% avg)")
                    else:
                        hook_list.append(str(h))
                insights_text.append(f"Previous high-performing hook styles: {', '.join(hook_list)}. Use similar patterns.")

            # Best topics
            topics = data.get("best_topic_keywords", [])
            if topics:
                good = [t["keyword"] for t in topics[:5] if isinstance(t, dict)]
                if good:
                    insights_text.append(f"High-engagement topic keywords: {', '.join(good)}. Weave these in when relevant.")

            # Best content types
            types = data.get("best_content_types", [])
            if types:
                type_list = []
                for t in types[:3]:
                    if isinstance(t, dict):
                        type_list.append(f"{t.get('type', '?')} ({t.get('avg_engagement', 0)}% avg)")
                if type_list:
                    insights_text.append(f"Best-performing formats: {', '.join(type_list)}.")

            # Recommendations
            recs = data.get("recommendations", [])
            if recs:
                insights_text.append("Performance recommendations:")
                for r in recs[:3]:
                    insights_text.append(f"  - {r}")

        except Exception:
            pass

    # Also check analytics directly for underperforming topics
    if ANALYTICS_FILE.exists():
        try:
            with open(ANALYTICS_FILE) as f:
                analytics = json.load(f)
            posts = analytics.get("posts", [])
            if len(posts) >= 5:
                # Find low performers
                sorted_posts = sorted(posts, key=lambda p: p.get("engagement_rate", 0))
                bottom = sorted_posts[:3]
                bottom_topics = [p.get("topic", "") for p in bottom if p.get("topic")]
                if bottom_topics:
                    insights_text.append(
                        f"Topics that underperformed: {', '.join(bottom_topics[:3])}. "
                        "Avoid these angles or find a fresh take."
                    )
        except Exception:
            pass

    return "\n".join(insights_text) if insights_text else ""


def _voice_check_output(script: dict) -> dict:
    """Run Voice Bible check on generated script text and auto-fix violations."""
    try:
        sys.path.insert(0, str(TOOLS_DIR))
        from voice_checker import fix_text
    except ImportError:
        return script

    # Check and fix all text fields
    text_fields = ["hook", "narration", "cta"]
    for key in text_fields:
        if key in script and isinstance(script[key], str):
            fixed, _ = fix_text(script[key])
            script[key] = fixed

    if "scenes" in script:
        for scene in script["scenes"]:
            for key in ["text", "overlay_text"]:
                if key in scene and isinstance(scene[key], str):
                    fixed, _ = fix_text(scene[key])
                    scene[key] = fixed

    return script


# --- System prompts (Dan Koe style, with Voice Bible injection) ---

def _build_system_prompt(language: str) -> str:
    """Build the system prompt with Voice Bible rules and performance data injected."""
    # Base prompt
    if language == "es":
        base = """Eres un escritor de guiones para videos cortos.
Voz: Directo, seguro, sin relleno. Un constructor hablando con constructores.
Estilo: Dan Koe mezclado con Naval Ravikant. Oraciones cortas. Sin fluff. Sin palabras de hype como "increible" o "espectacular."
Reglas:
- Cada oracion debe ganarse su lugar. Corta todo lo que no aporte valor.
- Usa "tu" para dirigirte al espectador directamente.
- No uses guiones largos. Usa puntos o comas.
- No uses emojis en los guiones.
- Empieza con un gancho que detenga el scroll. Que el espectador se sienta tonto por seguir pasando.
- Termina con un CTA claro: seguir, guardar, o compartir.
- Escribe para ser hablado. Oraciones cortas. Ritmo natural.
- Incluye descripciones visuales para cada escena (lo que aparece en pantalla).
- Manten el texto superpuesto en menos de 60 caracteres por escena.
Formato de salida: Devuelve SOLO JSON valido segun el esquema proporcionado. Sin markdown, sin explicacion."""
    else:
        base = """You are a script writer for short-form video content.
Voice: Direct, confident, zero filler. Builder talking to builders.
Style: Dan Koe meets Naval Ravikant. Short sentences. No fluff. No hype words like "amazing" or "incredible."
Rules:
- Every sentence must earn its place. Cut anything that does not add value.
- Use "you" to address the viewer directly.
- No em dashes. Use periods or commas instead.
- No emojis in scripts.
- Start with a hook that stops the scroll. Make the viewer feel stupid for scrolling past.
- End with a clear CTA: follow, save, or share.
- Write for spoken delivery. Short sentences. Natural rhythm.
- Include visual descriptions for each scene (what appears on screen).
- Keep overlay text under 60 characters per scene.
Output format: Return ONLY valid JSON matching the schema provided. No markdown, no explanation."""

    # Inject Voice Bible banned words
    voice_rules = load_voice_bible_rules()
    if voice_rules:
        base += f"\n\n## VOICE BIBLE (MANDATORY)\n{voice_rules}"

    # Inject performance insights
    perf = load_full_performance_insights()
    if perf:
        base += f"\n\n## PERFORMANCE DATA (use to optimize content)\n{perf}"

    return base


# Keep legacy constants for backward compat (used nowhere now, but safe)
SYSTEM_PROMPT_EN = """You are a script writer for short-form video content.
Voice: Direct, confident, zero filler. Builder talking to builders.
Style: Dan Koe meets Naval Ravikant. Short sentences. No fluff. No hype words like "amazing" or "incredible."
Rules:
- Every sentence must earn its place. Cut anything that does not add value.
- Use "you" to address the viewer directly.
- No em dashes. Use periods or commas instead.
- No emojis in scripts.
- Start with a hook that stops the scroll. Make the viewer feel stupid for scrolling past.
- End with a clear CTA: follow, save, or share.
- Write for spoken delivery. Short sentences. Natural rhythm.
- Include visual descriptions for each scene (what appears on screen).
- Keep overlay text under 60 characters per scene.
Output format: Return ONLY valid JSON matching the schema provided. No markdown, no explanation."""

SYSTEM_PROMPT_ES = """Eres un escritor de guiones para videos cortos.
Voz: Directo, seguro, sin relleno. Un constructor hablando con constructores.
Estilo: Dan Koe mezclado con Naval Ravikant. Oraciones cortas. Sin fluff. Sin palabras de hype como "increible" o "espectacular."
Reglas:
- Cada oracion debe ganarse su lugar. Corta todo lo que no aporte valor.
- Usa "tu" para dirigirte al espectador directamente.
- No uses guiones largos. Usa puntos o comas.
- No uses emojis en los guiones.
- Empieza con un gancho que detenga el scroll. Que el espectador se sienta tonto por seguir pasando.
- Termina con un CTA claro: seguir, guardar, o compartir.
- Escribe para ser hablado. Oraciones cortas. Ritmo natural.
- Incluye descripciones visuales para cada escena (lo que aparece en pantalla).
- Manten el texto superpuesto en menos de 60 caracteres por escena.
Formato de salida: Devuelve SOLO JSON valido segun el esquema proporcionado. Sin markdown, sin explicacion."""


def _build_prompt(topic: str, fmt: str, language: str, insights: str = "") -> str:
    """Build the user prompt for script generation."""
    format_info = FORMATS[fmt]
    lang_label = "Spanish (Latin American)" if language == "es" else "English"

    insight_block = ""
    if insights:
        insight_block = f"""
Use these performance insights to guide your writing:
{insights}
"""

    return f"""Write a {format_info['duration']} video script about: "{topic}"

Language: {lang_label}
Format: {format_info['name']}
Structure: {format_info['structure']}
Number of scenes: {format_info['scenes']}
{insight_block}
Return a JSON object with this exact schema:
{{
  "title": "slug-format-title",
  "hook": "The opening line (first 3 seconds)",
  "narration": "Full narration text, all scenes combined",
  "scenes": [
    {{
      "text": "Narration text for this scene",
      "image_prompt": "Visual description for image generation. Cinematic, 4k, specific details.",
      "overlay_text": "Short text overlay (max 60 chars)",
      "duration": 5
    }}
  ],
  "tags": ["relevant", "hashtag", "words"],
  "category": "content-category",
  "language": "{language}",
  "cta": "The call to action line"
}}

Remember: {format_info['description']}"""


def query_ollama(system_prompt: str, user_prompt: str) -> str:
    """Send a prompt to Ollama and return the response text."""
    payload = {
        "model": OLLAMA_MODEL,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "stream": False,
        "options": {
            "temperature": 0.7,
            "num_predict": 2048,
        },
    }

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{OLLAMA_URL}/api/chat",
        data=data,
        headers={"Content-Type": "application/json"},
    )

    try:
        with urllib.request.urlopen(req, timeout=120) as resp:
            result = json.loads(resp.read())
            return result.get("message", {}).get("content", "")
    except urllib.error.URLError as e:
        print(f"[ERROR] Cannot connect to Ollama at {OLLAMA_URL}")
        print(f"  Make sure Ollama is running: ollama serve")
        print(f"  Error: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"[ERROR] Ollama request failed: {e}")
        sys.exit(1)


def parse_script_json(raw: str) -> dict:
    """Extract and parse JSON from LLM response, handling markdown fences."""
    # Strip markdown code fences if present
    cleaned = raw.strip()
    if cleaned.startswith("```"):
        # Remove opening fence (```json or ```)
        cleaned = re.sub(r"^```(?:json)?\s*\n?", "", cleaned)
        # Remove closing fence
        cleaned = re.sub(r"\n?```\s*$", "", cleaned)

    # Try to find JSON object in the text
    brace_start = cleaned.find("{")
    brace_end = cleaned.rfind("}")
    if brace_start >= 0 and brace_end > brace_start:
        cleaned = cleaned[brace_start:brace_end + 1]

    try:
        return json.loads(cleaned)
    except json.JSONDecodeError as e:
        print(f"[ERROR] Failed to parse LLM output as JSON: {e}")
        print(f"  Raw output (first 500 chars): {raw[:500]}")
        return {}


def load_performance_insights() -> str:
    """Load top-performing content insights from analytics to inform script writing."""
    if not ANALYTICS_FILE.exists():
        return ""

    try:
        with open(ANALYTICS_FILE) as f:
            data = json.load(f)

        posts = data.get("posts", [])
        if not posts:
            return ""

        # Find top posts by engagement
        scored = []
        for p in posts:
            eng = p.get("engagement_rate", 0)
            if eng > 0:
                scored.append(p)

        if not scored:
            return ""

        scored.sort(key=lambda x: x.get("engagement_rate", 0), reverse=True)
        top = scored[:5]

        lines = ["Top performing content patterns:"]
        for p in top:
            lines.append(f"- Topic: {p.get('topic', 'unknown')}, "
                         f"Type: {p.get('content_type', '?')}, "
                         f"Engagement: {p.get('engagement_rate', 0):.1f}%")
            if p.get("hook_style"):
                lines.append(f"  Hook style: {p['hook_style']}")

        return "\n".join(lines)
    except Exception:
        return ""


def load_generated_log() -> dict:
    """Load the log of previously generated scripts to avoid duplicates."""
    if GENERATED_LOG.exists():
        try:
            with open(GENERATED_LOG) as f:
                return json.load(f)
        except Exception:
            pass
    return {"generated": []}


def save_generated_log(log: dict):
    """Save the generated scripts log."""
    GENERATED_LOG.parent.mkdir(parents=True, exist_ok=True)
    with open(GENERATED_LOG, "w") as f:
        json.dump(log, f, indent=2, default=str)


def generate_script(topic: str, fmt: str = "hook", language: str = "en") -> dict:
    """Generate a video script using Ollama. Injects Voice Bible and performance data."""
    sys_prompt = _build_system_prompt(language)
    insights = load_performance_insights()
    user_prompt = _build_prompt(topic, fmt, language, insights)

    print(f"  [AI] Generating {FORMATS[fmt]['name']} script ({language})...")
    print(f"  [AI] Model: {OLLAMA_MODEL} @ {OLLAMA_URL}")

    raw = query_ollama(sys_prompt, user_prompt)
    script = parse_script_json(raw)

    if not script:
        print("  [!] Script generation failed. Check Ollama output.")
        return {}

    # Ensure required fields
    script.setdefault("language", language)
    script.setdefault("tags", [])
    script.setdefault("category", "content")

    # Add metadata
    script["metadata"] = {
        "format": fmt,
        "format_name": FORMATS[fmt]["name"],
        "target_duration": FORMATS[fmt]["duration"],
        "model": OLLAMA_MODEL,
        "generated": datetime.now().isoformat(),
        "topic_input": topic,
        "voice": "af_heart" if language == "en" else "af_heart",
        "speed": 0.95,
    }

    # Clean em dashes from all text fields
    for key in ["hook", "narration", "cta"]:
        if key in script and isinstance(script[key], str):
            script[key] = script[key].replace("\u2014", ".").replace("\u2013", ".")
            while ".." in script[key]:
                script[key] = script[key].replace("..", ".")

    if "scenes" in script:
        for scene in script["scenes"]:
            for key in ["text", "overlay_text", "image_prompt"]:
                if key in scene and isinstance(scene[key], str):
                    scene[key] = scene[key].replace("\u2014", ".").replace("\u2013", ".")
                    while ".." in scene[key]:
                        scene[key] = scene[key].replace("..", ".")

    # Voice Bible post-generation check: catch anything the LLM slipped through
    script = _voice_check_output(script)

    return script


def save_script(script: dict, output_dir: Path = None) -> Path:
    """Save a script to disk. Returns the file path."""
    if output_dir is None:
        output_dir = SCRIPTS_DIR

    output_dir.mkdir(parents=True, exist_ok=True)

    title = script.get("title", "untitled")
    # Sanitize title for filename
    safe_title = re.sub(r"[^a-z0-9_-]", "", title.lower().replace(" ", "-"))[:50]
    lang = script.get("language", "en")
    fmt = script.get("metadata", {}).get("format", "hook")
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")

    filename = f"script-{safe_title}-{fmt}-{lang}-{timestamp}.json"
    filepath = output_dir / filename

    with open(filepath, "w") as f:
        json.dump(script, f, indent=2, ensure_ascii=False)

    return filepath


def save_to_reel_pipeline(script: dict) -> Path:
    """Save script in reel-pipeline stories format for video production."""
    REEL_STORIES_DIR.mkdir(parents=True, exist_ok=True)

    title = script.get("title", "untitled")
    safe_title = re.sub(r"[^a-z0-9_-]", "", title.lower().replace(" ", "-"))[:50]

    filepath = REEL_STORIES_DIR / f"script-{safe_title}.json"

    # Convert to reel-pipeline format
    reel_data = {
        "title": title,
        "hook": script.get("hook", ""),
        "narration": script.get("narration", ""),
        "scenes": script.get("scenes", []),
        "tags": script.get("tags", []),
        "category": script.get("category", "content"),
        "language": script.get("language", "en"),
    }

    with open(filepath, "w") as f:
        json.dump(reel_data, f, indent=2, ensure_ascii=False)

    return filepath


def pick_from_ideas(count: int = 1) -> list:
    """Pick random topics from the content ideas database."""
    if not IDEAS_FILE.exists():
        print("[!] No content ideas found. Run: python3 content_extractor.py --scan")
        return []

    with open(IDEAS_FILE) as f:
        data = json.load(f)

    ideas = data.get("ideas", [])
    if not ideas:
        print("[!] Content ideas database is empty.")
        return []

    # Filter out already-generated topics
    log = load_generated_log()
    generated_ids = {g.get("idea_id") for g in log.get("generated", [])}
    available = [i for i in ideas if i.get("id") not in generated_ids]

    if not available:
        print("[!] All ideas have been used. Resetting tracker.")
        available = ideas

    count = min(count, len(available))
    return random.sample(available, count)


def main():
    parser = argparse.ArgumentParser(
        description="AI Script Generator. Uses Ollama to write video scripts. Copyright 2026 Behike."
    )
    parser.add_argument("--topic", type=str, help="Topic to write about")
    parser.add_argument("--format", dest="fmt", choices=list(FORMATS.keys()),
                        default="hook", help="Script format (default: hook)")
    parser.add_argument("--language", choices=["en", "es"], default="en",
                        help="Output language (default: en)")
    parser.add_argument("--both-languages", action="store_true",
                        help="Generate both EN and ES versions")
    parser.add_argument("--from-ideas", action="store_true",
                        help="Pick random topic from content-ideas.json")
    parser.add_argument("--count", type=int, default=1,
                        help="Number of scripts to generate (default: 1)")
    parser.add_argument("--output", type=str, help="Custom output directory")
    parser.add_argument("--reel", action="store_true",
                        help="Also save to reel-pipeline stories directory")
    parser.add_argument("--list-formats", action="store_true",
                        help="Show available script formats")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be generated without calling Ollama")

    args = parser.parse_args()

    if args.list_formats:
        print("\nAvailable script formats:\n")
        for key, fmt in FORMATS.items():
            print(f"  {key:10s}  {fmt['name']} ({fmt['duration']})")
            print(f"             {fmt['structure']}")
            print(f"             {fmt['description']}")
            print()
        return

    # Collect topics
    topics = []
    idea_map = {}

    if args.from_ideas:
        ideas = pick_from_ideas(args.count)
        for idea in ideas:
            t = idea.get("title", "")
            topics.append(t)
            idea_map[t] = idea
    elif args.topic:
        topics = [args.topic] * args.count
    else:
        parser.print_help()
        return

    if not topics:
        return

    output_dir = Path(args.output) if args.output else SCRIPTS_DIR
    log = load_generated_log()

    print()
    print("=" * 60)
    print("  BEHIKE SCRIPT WRITER")
    print("=" * 60)
    print(f"  Topics:   {len(topics)}")
    print(f"  Format:   {FORMATS[args.fmt]['name']} ({FORMATS[args.fmt]['duration']})")
    print(f"  Language: {'EN + ES' if args.both_languages else args.language.upper()}")
    print(f"  Model:    {OLLAMA_MODEL}")
    print()

    generated_files = []

    for i, topic in enumerate(topics, 1):
        print(f"[{i}/{len(topics)}] {topic}")

        if args.dry_run:
            print(f"  [DRY RUN] Would generate {args.fmt} script")
            if args.both_languages:
                print(f"  [DRY RUN] Would generate ES version too")
            continue

        languages = ["en", "es"] if args.both_languages else [args.language]

        for lang in languages:
            script = generate_script(topic, args.fmt, lang)
            if not script:
                continue

            filepath = save_script(script, output_dir)
            generated_files.append(filepath)
            print(f"  [SAVED] {filepath}")

            if args.reel:
                reel_path = save_to_reel_pipeline(script)
                print(f"  [REEL]  {reel_path}")

            # Log generation
            log_entry = {
                "topic": topic,
                "format": args.fmt,
                "language": lang,
                "file": str(filepath),
                "generated_at": datetime.now().isoformat(),
            }
            if topic in idea_map:
                log_entry["idea_id"] = idea_map[topic].get("id", "")
            log["generated"].append(log_entry)

        print()

    save_generated_log(log)

    print("=" * 60)
    print(f"  DONE. Generated {len(generated_files)} scripts.")
    if generated_files:
        print(f"  Output: {output_dir}/")
        if args.reel:
            print(f"  Reel pipeline: {REEL_STORIES_DIR}/")
    print("=" * 60)
    print()


if __name__ == "__main__":
    main()
